/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for CollectionMetadataDto */
class CollectionMetadataDtoTest {
    private final CollectionMetadataDto model = new CollectionMetadataDto();

    /** Model tests for CollectionMetadataDto */
    @Test
    void testCollectionMetadataDto() {
        // TODO: test CollectionMetadataDto
    }

    /** Test the property 'fbCollectionId' */
    @Test
    void fbCollectionIdTest() {
        // TODO: test fbCollectionId
    }

    /** Test the property 'name' */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /** Test the property 'symbol' */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /** Test the property 'standard' */
    @Test
    void standardTest() {
        // TODO: test standard
    }

    /** Test the property 'blockchainDescriptor' */
    @Test
    void blockchainDescriptorTest() {
        // TODO: test blockchainDescriptor
    }

    /** Test the property 'contractAddress' */
    @Test
    void contractAddressTest() {
        // TODO: test contractAddress
    }
}
