/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for CreateVaultAccountConnectionRequest */
class CreateVaultAccountConnectionRequestTest {
    private final CreateVaultAccountConnectionRequest model =
            new CreateVaultAccountConnectionRequest();

    /** Model tests for CreateVaultAccountConnectionRequest */
    @Test
    void testCreateVaultAccountConnectionRequest() {
        // TODO: test CreateVaultAccountConnectionRequest
    }

    /** Test the property 'vaultAccountId' */
    @Test
    void vaultAccountIdTest() {
        // TODO: test vaultAccountId
    }

    /** Test the property 'feeLevel' */
    @Test
    void feeLevelTest() {
        // TODO: test feeLevel
    }

    /** Test the property 'uri' */
    @Test
    void uriTest() {
        // TODO: test uri
    }

    /** Test the property 'chainIds' */
    @Test
    void chainIdsTest() {
        // TODO: test chainIds
    }
}
