/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for CreateAPIUser */
class CreateAPIUserTest {
    private final CreateAPIUser model = new CreateAPIUser();

    /** Model tests for CreateAPIUser */
    @Test
    void testCreateAPIUser() {
        // TODO: test CreateAPIUser
    }

    /** Test the property 'role' */
    @Test
    void roleTest() {
        // TODO: test role
    }

    /** Test the property 'name' */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /** Test the property 'csrPem' */
    @Test
    void csrPemTest() {
        // TODO: test csrPem
    }

    /** Test the property 'coSignerSetupType' */
    @Test
    void coSignerSetupTypeTest() {
        // TODO: test coSignerSetupType
    }

    /** Test the property 'coSignerSetupIsFirstUser' */
    @Test
    void coSignerSetupIsFirstUserTest() {
        // TODO: test coSignerSetupIsFirstUser
    }
}
