/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fireblocks.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for DeployedContractResponseDto
 */
public class DeployedContractResponseDtoTest {
    private final DeployedContractResponseDto model = new DeployedContractResponseDto();

    /**
     * Model tests for DeployedContractResponseDto
     */
    @Test
    public void testDeployedContractResponseDto() {
        // TODO: test DeployedContractResponseDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'contractTemplateId'
     */
    @Test
    public void contractTemplateIdTest() {
        // TODO: test contractTemplateId
    }

    /**
     * Test the property 'vaultAccountId'
     */
    @Test
    public void vaultAccountIdTest() {
        // TODO: test vaultAccountId
    }

    /**
     * Test the property 'blockchainId'
     */
    @Test
    public void blockchainIdTest() {
        // TODO: test blockchainId
    }

}
