/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for EmbeddedWalletPaginatedAddressesResponse */
class EmbeddedWalletPaginatedAddressesResponseTest {
    private final EmbeddedWalletPaginatedAddressesResponse model =
            new EmbeddedWalletPaginatedAddressesResponse();

    /** Model tests for EmbeddedWalletPaginatedAddressesResponse */
    @Test
    void testEmbeddedWalletPaginatedAddressesResponse() {
        // TODO: test EmbeddedWalletPaginatedAddressesResponse
    }

    /** Test the property 'data' */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /** Test the property 'next' */
    @Test
    void nextTest() {
        // TODO: test next
    }
}
