/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for GetMaxBipIndexUsedResponse */
class GetMaxBipIndexUsedResponseTest {
    private final GetMaxBipIndexUsedResponse model = new GetMaxBipIndexUsedResponse();

    /** Model tests for GetMaxBipIndexUsedResponse */
    @Test
    void testGetMaxBipIndexUsedResponse() {
        // TODO: test GetMaxBipIndexUsedResponse
    }

    /** Test the property 'maxBip44AddressIndexUsed' */
    @Test
    void maxBip44AddressIndexUsedTest() {
        // TODO: test maxBip44AddressIndexUsed
    }

    /** Test the property 'maxBip44ChangeAddressIndexUsed' */
    @Test
    void maxBip44ChangeAddressIndexUsedTest() {
        // TODO: test maxBip44ChangeAddressIndexUsed
    }
}
