/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for IbanPaymentInfo */
class IbanPaymentInfoTest {
    private final IbanPaymentInfo model = new IbanPaymentInfo();

    /** Model tests for IbanPaymentInfo */
    @Test
    void testIbanPaymentInfo() {
        // TODO: test IbanPaymentInfo
    }

    /** Test the property 'accountHolderGivenName' */
    @Test
    void accountHolderGivenNameTest() {
        // TODO: test accountHolderGivenName
    }

    /** Test the property 'accountHolderSurname' */
    @Test
    void accountHolderSurnameTest() {
        // TODO: test accountHolderSurname
    }

    /** Test the property 'accountHolderCity' */
    @Test
    void accountHolderCityTest() {
        // TODO: test accountHolderCity
    }

    /** Test the property 'accountHolderCountry' */
    @Test
    void accountHolderCountryTest() {
        // TODO: test accountHolderCountry
    }

    /** Test the property 'accountHolderAddress1' */
    @Test
    void accountHolderAddress1Test() {
        // TODO: test accountHolderAddress1
    }

    /** Test the property 'accountHolderAddress2' */
    @Test
    void accountHolderAddress2Test() {
        // TODO: test accountHolderAddress2
    }

    /** Test the property 'accountHolderDistrict' */
    @Test
    void accountHolderDistrictTest() {
        // TODO: test accountHolderDistrict
    }

    /** Test the property 'accountHolderPostalCode' */
    @Test
    void accountHolderPostalCodeTest() {
        // TODO: test accountHolderPostalCode
    }

    /** Test the property 'iban' */
    @Test
    void ibanTest() {
        // TODO: test iban
    }

    /** Test the property 'ibanCity' */
    @Test
    void ibanCityTest() {
        // TODO: test ibanCity
    }

    /** Test the property 'ibanCountry' */
    @Test
    void ibanCountryTest() {
        // TODO: test ibanCountry
    }
}
