/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for LegacyPolicyRuleAmountAggregation */
class LegacyPolicyRuleAmountAggregationTest {
    private final LegacyPolicyRuleAmountAggregation model = new LegacyPolicyRuleAmountAggregation();

    /** Model tests for LegacyPolicyRuleAmountAggregation */
    @Test
    void testLegacyPolicyRuleAmountAggregation() {
        // TODO: test LegacyPolicyRuleAmountAggregation
    }

    /** Test the property 'operators' */
    @Test
    void operatorsTest() {
        // TODO: test operators
    }

    /** Test the property 'srcTransferPeers' */
    @Test
    void srcTransferPeersTest() {
        // TODO: test srcTransferPeers
    }

    /** Test the property 'dstTransferPeers' */
    @Test
    void dstTransferPeersTest() {
        // TODO: test dstTransferPeers
    }
}
