/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for MpcKey */
class MpcKeyTest {
    private final MpcKey model = new MpcKey();

    /** Model tests for MpcKey */
    @Test
    void testMpcKey() {
        // TODO: test MpcKey
    }

    /** Test the property 'keyId' */
    @Test
    void keyIdTest() {
        // TODO: test keyId
    }

    /** Test the property 'userId' */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /** Test the property 'algorithm' */
    @Test
    void algorithmTest() {
        // TODO: test algorithm
    }

    /** Test the property 'players' */
    @Test
    void playersTest() {
        // TODO: test players
    }

    /** Test the property 'lastPreprocessedIndex' */
    @Test
    void lastPreprocessedIndexTest() {
        // TODO: test lastPreprocessedIndex
    }
}
