/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for PaginatedAddressResponsePaging */
class PaginatedAddressResponsePagingTest {
    private final PaginatedAddressResponsePaging model = new PaginatedAddressResponsePaging();

    /** Model tests for PaginatedAddressResponsePaging */
    @Test
    void testPaginatedAddressResponsePaging() {
        // TODO: test PaginatedAddressResponsePaging
    }

    /** Test the property 'before' */
    @Test
    void beforeTest() {
        // TODO: test before
    }

    /** Test the property 'after' */
    @Test
    void afterTest() {
        // TODO: test after
    }
}
