/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for PolicyRuleAmountAggregation */
class PolicyRuleAmountAggregationTest {
    private final PolicyRuleAmountAggregation model = new PolicyRuleAmountAggregation();

    /** Model tests for PolicyRuleAmountAggregation */
    @Test
    void testPolicyRuleAmountAggregation() {
        // TODO: test PolicyRuleAmountAggregation
    }

    /** Test the property 'operators' */
    @Test
    void operatorsTest() {
        // TODO: test operators
    }

    /** Test the property 'srcTransferPeers' */
    @Test
    void srcTransferPeersTest() {
        // TODO: test srcTransferPeers
    }

    /** Test the property 'dstTransferPeers' */
    @Test
    void dstTransferPeersTest() {
        // TODO: test dstTransferPeers
    }
}
