/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for PublishDraftRequest */
class PublishDraftRequestTest {
    private final PublishDraftRequest model = new PublishDraftRequest();

    /** Model tests for PublishDraftRequest */
    @Test
    void testPublishDraftRequest() {
        // TODO: test PublishDraftRequest
    }

    /** Test the property 'policyTypes' */
    @Test
    void policyTypesTest() {
        // TODO: test policyTypes
    }

    /** Test the property 'draftId' */
    @Test
    void draftIdTest() {
        // TODO: test draftId
    }
}
