/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for QuoteResponse */
class QuoteResponseTest {
    private final QuoteResponse model = new QuoteResponse();

    /** Model tests for QuoteResponse */
    @Test
    void testQuoteResponse() {
        // TODO: test QuoteResponse
    }

    /** Test the property 'protocol' */
    @Test
    void protocolTest() {
        // TODO: test protocol
    }

    /** Test the property 'inputAmount' */
    @Test
    void inputAmountTest() {
        // TODO: test inputAmount
    }

    /** Test the property 'inputAsset' */
    @Test
    void inputAssetTest() {
        // TODO: test inputAsset
    }

    /** Test the property 'slippageTolerance' */
    @Test
    void slippageToleranceTest() {
        // TODO: test slippageTolerance
    }

    /** Test the property 'outputMinAmount' */
    @Test
    void outputMinAmountTest() {
        // TODO: test outputMinAmount
    }

    /** Test the property 'outputMaxAmount' */
    @Test
    void outputMaxAmountTest() {
        // TODO: test outputMaxAmount
    }

    /** Test the property 'outputAsset' */
    @Test
    void outputAssetTest() {
        // TODO: test outputAsset
    }

    /** Test the property 'additionalData' */
    @Test
    void additionalDataTest() {
        // TODO: test additionalData
    }

    /** Test the property 'providerQuoteId' */
    @Test
    void providerQuoteIdTest() {
        // TODO: test providerQuoteId
    }

    /** Test the property 'expiredAt' */
    @Test
    void expiredAtTest() {
        // TODO: test expiredAt
    }

    /** Test the property 'requiredActions' */
    @Test
    void requiredActionsTest() {
        // TODO: test requiredActions
    }

    /** Test the property 'estimatedFees' */
    @Test
    void estimatedFeesTest() {
        // TODO: test estimatedFees
    }
}
