/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for RelatedRequest */
class RelatedRequestTest {
    private final RelatedRequest model = new RelatedRequest();

    /** Model tests for RelatedRequest */
    @Test
    void testRelatedRequest() {
        // TODO: test RelatedRequest
    }

    /** Test the property 'status' */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /** Test the property 'inProgress' */
    @Test
    void inProgressTest() {
        // TODO: test inProgress
    }

    /** Test the property 'amount' */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /** Test the property 'txId' */
    @Test
    void txIdTest() {
        // TODO: test txId
    }
}
