/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for ScreeningTravelRuleResult */
class ScreeningTravelRuleResultTest {
    private final ScreeningTravelRuleResult model = new ScreeningTravelRuleResult();

    /** Model tests for ScreeningTravelRuleResult */
    @Test
    void testScreeningTravelRuleResult() {
        // TODO: test ScreeningTravelRuleResult
    }

    /** Test the property 'direction' */
    @Test
    void directionTest() {
        // TODO: test direction
    }

    /** Test the property 'isVerified' */
    @Test
    void isVerifiedTest() {
        // TODO: test isVerified
    }

    /** Test the property 'action' */
    @Test
    void actionTest() {
        // TODO: test action
    }

    /** Test the property 'providerResponse' */
    @Test
    void providerResponseTest() {
        // TODO: test providerResponse
    }

    /** Test the property 'matchedRule' */
    @Test
    void matchedRuleTest() {
        // TODO: test matchedRule
    }
}
