/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for ScreeningTravelRuleMatchedRule */
class ScreeningTravelRuleMatchedRuleTest {
    private final ScreeningTravelRuleMatchedRule model = new ScreeningTravelRuleMatchedRule();

    /** Model tests for ScreeningTravelRuleMatchedRule */
    @Test
    void testScreeningTravelRuleMatchedRule() {
        // TODO: test ScreeningTravelRuleMatchedRule
    }

    /** Test the property 'direction' */
    @Test
    void directionTest() {
        // TODO: test direction
    }

    /** Test the property 'status' */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /** Test the property 'amountUSD' */
    @Test
    void amountUSDTest() {
        // TODO: test amountUSD
    }

    /** Test the property 'amount' */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /** Test the property 'asset' */
    @Test
    void assetTest() {
        // TODO: test asset
    }

    /** Test the property 'action' */
    @Test
    void actionTest() {
        // TODO: test action
    }
}
