/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for TokenLinkExistsHttpError */
class TokenLinkExistsHttpErrorTest {
    private final TokenLinkExistsHttpError model = new TokenLinkExistsHttpError();

    /** Model tests for TokenLinkExistsHttpError */
    @Test
    void testTokenLinkExistsHttpError() {
        // TODO: test TokenLinkExistsHttpError
    }

    /** Test the property 'statusCode' */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

    /** Test the property 'message' */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /** Test the property 'error' */
    @Test
    void errorTest() {
        // TODO: test error
    }
}
