/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.Test;

/** Model tests for TokenLinkRequestDto */
public class TokenLinkRequestDtoTest {
    private final TokenLinkRequestDto model = new TokenLinkRequestDto();

    /** Model tests for TokenLinkRequestDto */
    @Test
    public void testTokenLinkRequestDto() {
        // TODO: test TokenLinkRequestDto
    }

    /** Test the property 'type' */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /** Test the property 'refId' */
    @Test
    public void refIdTest() {
        // TODO: test refId
    }

    /** Test the property 'displayName' */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /** Test the property 'baseAssetId' */
    @Test
    public void baseAssetIdTest() {
        // TODO: test baseAssetId
    }

    /** Test the property 'contractAddress' */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }
}
