/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for TravelRuleVASPExternalEntity */
class TravelRuleVASPExternalEntityTest {
    private final TravelRuleVASPExternalEntity model = new TravelRuleVASPExternalEntity();

    /** Model tests for TravelRuleVASPExternalEntity */
    @Test
    void testTravelRuleVASPExternalEntity() {
        // TODO: test TravelRuleVASPExternalEntity
    }

    /** Test the property 'legalName' */
    @Test
    void legalNameTest() {
        // TODO: test legalName
    }

    /** Test the property 'otherLegalName' */
    @Test
    void otherLegalNameTest() {
        // TODO: test otherLegalName
    }

    /** Test the property 'legalForm' */
    @Test
    void legalFormTest() {
        // TODO: test legalForm
    }

    /** Test the property 'legalStructure' */
    @Test
    void legalStructureTest() {
        // TODO: test legalStructure
    }

    /** Test the property 'entityCategory' */
    @Test
    void entityCategoryTest() {
        // TODO: test entityCategory
    }

    /** Test the property 'entityStatus' */
    @Test
    void entityStatusTest() {
        // TODO: test entityStatus
    }

    /** Test the property 'businessNumber' */
    @Test
    void businessNumberTest() {
        // TODO: test businessNumber
    }

    /** Test the property 'yearFounded' */
    @Test
    void yearFoundedTest() {
        // TODO: test yearFounded
    }

    /** Test the property 'jurisdictions' */
    @Test
    void jurisdictionsTest() {
        // TODO: test jurisdictions
    }

    /** Test the property 'addressLine1' */
    @Test
    void addressLine1Test() {
        // TODO: test addressLine1
    }

    /** Test the property 'number' */
    @Test
    void numberTest() {
        // TODO: test number
    }

    /** Test the property 'postCode' */
    @Test
    void postCodeTest() {
        // TODO: test postCode
    }

    /** Test the property 'city' */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /** Test the property 'state' */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /** Test the property 'country' */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /** Test the property 'hqStreet' */
    @Test
    void hqStreetTest() {
        // TODO: test hqStreet
    }

    /** Test the property 'hqNumber' */
    @Test
    void hqNumberTest() {
        // TODO: test hqNumber
    }

    /** Test the property 'hqPostcode' */
    @Test
    void hqPostcodeTest() {
        // TODO: test hqPostcode
    }

    /** Test the property 'hqCity' */
    @Test
    void hqCityTest() {
        // TODO: test hqCity
    }

    /** Test the property 'hqRegion' */
    @Test
    void hqRegionTest() {
        // TODO: test hqRegion
    }

    /** Test the property 'hqCountry' */
    @Test
    void hqCountryTest() {
        // TODO: test hqCountry
    }
}
