/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import org.junit.jupiter.api.Test;

/** Model tests for UpdateTagRequest */
class UpdateTagRequestTest {
    private final UpdateTagRequest model = new UpdateTagRequest();

    /** Model tests for UpdateTagRequest */
    @Test
    void testUpdateTagRequest() {
        // TODO: test UpdateTagRequest
    }

    /** Test the property 'label' */
    @Test
    void labelTest() {
        // TODO: test label
    }

    /** Test the property 'description' */
    @Test
    void descriptionTest() {
        // TODO: test description
    }
}
