/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.api;


import com.fireblocks.sdk.ApiException;
import com.fireblocks.sdk.ApiResponse;
import com.fireblocks.sdk.model.ScreeningConfigurationsRequest;
import java.util.concurrent.CompletableFuture;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for ComplianceScreeningConfigurationApi */
@Ignore
public class ComplianceScreeningConfigurationApiTest {

    private final ComplianceScreeningConfigurationApi api =
            new ComplianceScreeningConfigurationApi();

    /**
     * Get AML Screening Policy Configuration
     *
     * <p>Retrieves the configuration for Travel Rule screening policy.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAmlScreeningConfigurationTest() throws ApiException {
        CompletableFuture<ApiResponse<ScreeningConfigurationsRequest>> response =
                api.getAmlScreeningConfiguration();
    }

    /**
     * Get Travel Rule Screening Policy Configuration
     *
     * <p>Retrieves the configuration for Travel Rule screening policy.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getScreeningConfigurationTest() throws ApiException {
        CompletableFuture<ApiResponse<ScreeningConfigurationsRequest>> response =
                api.getScreeningConfiguration();
    }
}
