/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fireblocks.sdk.ApiClient;
import java.util.Objects;
import java.util.StringJoiner;

/** The signed approval of a pending request. */
@JsonPropertyOrder({
    ApproveApprovalRequest.JSON_PROPERTY_KEY_ID,
    ApproveApprovalRequest.JSON_PROPERTY_SIGNATURE
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class ApproveApprovalRequest {
    public static final String JSON_PROPERTY_KEY_ID = "keyId";
    @jakarta.annotation.Nullable private String keyId;

    public static final String JSON_PROPERTY_SIGNATURE = "signature";
    @jakarta.annotation.Nonnull private String signature;

    public ApproveApprovalRequest() {}

    @JsonCreator
    public ApproveApprovalRequest(
            @JsonProperty(value = JSON_PROPERTY_SIGNATURE, required = true) String signature) {
        this.signature = signature;
    }

    public ApproveApprovalRequest keyId(@jakarta.annotation.Nullable String keyId) {
        this.keyId = keyId;
        return this;
    }

    /**
     * The ID of the approval API key used to sign the request. Optional — if omitted, the signature
     * is verified against all of the user&#39;s registered approval API keys.
     *
     * @return keyId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_KEY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getKeyId() {
        return keyId;
    }

    @JsonProperty(JSON_PROPERTY_KEY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeyId(@jakarta.annotation.Nullable String keyId) {
        this.keyId = keyId;
    }

    public ApproveApprovalRequest signature(@jakarta.annotation.Nonnull String signature) {
        this.signature = signature;
        return this;
    }

    /**
     * Base64url-encoded signature over the request&#39;s signable data, produced with the private
     * key of a registered approval API key. If keyId is provided the signature must match that key;
     * otherwise it is matched against all of the user&#39;s registered keys.
     *
     * @return signature
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_SIGNATURE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getSignature() {
        return signature;
    }

    @JsonProperty(JSON_PROPERTY_SIGNATURE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSignature(@jakarta.annotation.Nonnull String signature) {
        this.signature = signature;
    }

    /** Return true if this ApproveApprovalRequest object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApproveApprovalRequest approveApprovalRequest = (ApproveApprovalRequest) o;
        return Objects.equals(this.keyId, approveApprovalRequest.keyId)
                && Objects.equals(this.signature, approveApprovalRequest.signature);
    }

    @Override
    public int hashCode() {
        return Objects.hash(keyId, signature);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApproveApprovalRequest {\n");
        sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
        sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `keyId` to the URL query string
        if (getKeyId() != null) {
            joiner.add(
                    String.format(
                            "%skeyId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getKeyId()))));
        }

        // add `signature` to the URL query string
        if (getSignature() != null) {
            joiner.add(
                    String.format(
                            "%ssignature%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getSignature()))));
        }

        return joiner.toString();
    }
}
