/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

/** CollectionTokenMetadataAttributeDto */
@JsonPropertyOrder({
    CollectionTokenMetadataAttributeDto.JSON_PROPERTY_TRAIT_TYPE,
    CollectionTokenMetadataAttributeDto.JSON_PROPERTY_VALUE,
    CollectionTokenMetadataAttributeDto.JSON_PROPERTY_DISPLAY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CollectionTokenMetadataAttributeDto {
    public static final String JSON_PROPERTY_TRAIT_TYPE = "trait_type";
    private String traitType;

    public static final String JSON_PROPERTY_VALUE = "value";
    private String value;

    public static final String JSON_PROPERTY_DISPLAY_TYPE = "display_type";
    private String displayType;

    public CollectionTokenMetadataAttributeDto() {}

    public CollectionTokenMetadataAttributeDto traitType(String traitType) {
        this.traitType = traitType;
        return this;
    }

    /**
     * Name of the trait
     *
     * @return traitType
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TRAIT_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getTraitType() {
        return traitType;
    }

    @JsonProperty(JSON_PROPERTY_TRAIT_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTraitType(String traitType) {
        this.traitType = traitType;
    }

    public CollectionTokenMetadataAttributeDto value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Value of the trait
     *
     * @return value
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getValue() {
        return value;
    }

    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setValue(String value) {
        this.value = value;
    }

    public CollectionTokenMetadataAttributeDto displayType(String displayType) {
        this.displayType = displayType;
        return this;
    }

    /**
     * A field indicating how you would like trait to be displayed
     *
     * @return displayType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISPLAY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDisplayType() {
        return displayType;
    }

    @JsonProperty(JSON_PROPERTY_DISPLAY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisplayType(String displayType) {
        this.displayType = displayType;
    }

    /** Return true if this CollectionTokenMetadataAttributeDto object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CollectionTokenMetadataAttributeDto collectionTokenMetadataAttributeDto =
                (CollectionTokenMetadataAttributeDto) o;
        return Objects.equals(this.traitType, collectionTokenMetadataAttributeDto.traitType)
                && Objects.equals(this.value, collectionTokenMetadataAttributeDto.value)
                && Objects.equals(
                        this.displayType, collectionTokenMetadataAttributeDto.displayType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(traitType, value, displayType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CollectionTokenMetadataAttributeDto {\n");
        sb.append("    traitType: ").append(toIndentedString(traitType)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    displayType: ").append(toIndentedString(displayType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `trait_type` to the URL query string
        if (getTraitType() != null) {
            joiner.add(
                    String.format(
                            "%strait_type%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(
                                            String.valueOf(getTraitType()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `value` to the URL query string
        if (getValue() != null) {
            joiner.add(
                    String.format(
                            "%svalue%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getValue()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `display_type` to the URL query string
        if (getDisplayType() != null) {
            joiner.add(
                    String.format(
                            "%sdisplay_type%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(
                                            String.valueOf(getDisplayType()),
                                            StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
