/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Status of compliance result screening */
public enum ComplianceResultStatusesEnum {
    UNKNOWN("Unknown"),

    STALLED("Stalled"),

    STARTED("Started"),

    NETWORK_CONNECTION_ADDRESS_RESOLVE("NetworkConnectionAddressResolve"),

    SCREENING_PREPARE("ScreeningPrepare"),

    AML_STARTED("AMLStarted"),

    AML_COMPLETED("AMLCompleted"),

    AML_FAILED("AMLFailed"),

    AMLIN_BACKGROUND("AMLInBackground"),

    TR_PRECONDITION_CHECKS("TRPreconditionChecks"),

    TR_STARTED("TRStarted"),

    TR_LINK_STARTED("TRLinkStarted"),

    TR_LINK_DESTINATION_STARTED("TRLinkDestinationStarted"),

    TR_LINK_DESTINATION_PRESCREEN_POLICY("TRLinkDestinationPrescreenPolicy"),

    TR_LINK_DESTINATION_NO_TRM_POLICY("TRLinkDestinationNoTRMPolicy"),

    TR_LINK_DESTINATION_SCREEN("TRLinkDestinationScreen"),

    TR_LINK_DESTINATION_POSTSCREEN_POLICY("TRLinkDestinationPostscreenPolicy"),

    TR_LINK_DESTINATION_COMPLETED("TRLinkDestinationCompleted"),

    TR_LINK_COMPLETED("TRLinkCompleted"),

    TR_COMPLETED("TRCompleted"),

    TR_FAILED("TRFailed"),

    COMPLETED("Completed"),

    REGISTRATION_STARTED("RegistrationStarted"),

    REGISTRATION_WAIT_FOR_FIRST_CONFIRMATION("RegistrationWaitForFirstConfirmation"),

    AML_REGISTRATION_STARTED("AMLRegistrationStarted"),

    AML_REGISTRATION_COMPLETED("AMLRegistrationCompleted"),

    TR_UPDATE_STARTED("TRUpdateStarted"),

    TR_UPDATE_COMPLETED("TRUpdateCompleted"),

    UPDATE_COMPLETED("UpdateCompleted"),

    INCOMING_STARTED("IncomingStarted"),

    INCOMING_BYORK_SL("IncomingByorkSL"),

    INCOMING_SCREENING_PREPARE("IncomingScreeningPrepare"),

    INCOMING_WAIT_FOR_FIRST_CONFIRMATION("IncomingWaitForFirstConfirmation"),

    AML_INCOMING_STARTED("AMLIncomingStarted"),

    AML_INCOMING_COMPLETED("AMLIncomingCompleted"),

    AML_INCOMING_FAILED("AMLIncomingFailed"),

    AML_INCOMING_IN_BACKGROUND("AMLIncomingInBackground"),

    TR_INCOMING_STARTED("TRIncomingStarted"),

    TR_INCOMING_COMPLETED("TRIncomingCompleted"),

    TR_INCOMING_FAILED("TRIncomingFailed"),

    INCOMING_COMPLETED("IncomingCompleted"),

    ADDRESS_AML_INITIATED("AddressAmlInitiated"),

    ADDRESS_AML_ADDRESS_RESOLVE("AddressAmlAddressResolve"),

    ADDRESS_AML_PREPARE("AddressAmlPrepare"),

    ADDRESS_AML_PROCESSING("AddressAmlProcessing"),

    ADDRESS_AML_SUCCEEDED("AddressAmlSucceeded"),

    ADDRESS_AML_FAILED("AddressAmlFailed"),

    ADDRESS_AML_COMPLETED("AddressAmlCompleted");

    private String value;

    ComplianceResultStatusesEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static ComplianceResultStatusesEnum fromValue(String value) {
        for (ComplianceResultStatusesEnum b : ComplianceResultStatusesEnum.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        if (prefix == null) {
            prefix = "";
        }

        return String.format("%s=%s", prefix, this.toString());
    }
}
