/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fireblocks.sdk.ApiClient;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/** Request body for creating a Tempo transfer transaction. */
@JsonPropertyOrder({
    CreateTempoTransferRequest.JSON_PROPERTY_NOTE,
    CreateTempoTransferRequest.JSON_PROPERTY_EXTERNAL_TX_ID,
    CreateTempoTransferRequest.JSON_PROPERTY_FEE_CURRENCY,
    CreateTempoTransferRequest.JSON_PROPERTY_ASSET_ID,
    CreateTempoTransferRequest.JSON_PROPERTY_SOURCE,
    CreateTempoTransferRequest.JSON_PROPERTY_DESTINATION,
    CreateTempoTransferRequest.JSON_PROPERTY_AMOUNT,
    CreateTempoTransferRequest.JSON_PROPERTY_TREAT_AS_GROSS_AMOUNT,
    CreateTempoTransferRequest.JSON_PROPERTY_FEE_LEVEL,
    CreateTempoTransferRequest.JSON_PROPERTY_TRAVEL_RULE_MESSAGE,
    CreateTempoTransferRequest.JSON_PROPERTY_TRAVEL_RULE_MESSAGE_ID,
    CreateTempoTransferRequest.JSON_PROPERTY_USE_GASLESS,
    CreateTempoTransferRequest.JSON_PROPERTY_CONFIGURATIONS,
    CreateTempoTransferRequest.JSON_PROPERTY_MAX_FEE_PER_GAS,
    CreateTempoTransferRequest.JSON_PROPERTY_MAX_PRIORITY_FEE_PER_GAS,
    CreateTempoTransferRequest.JSON_PROPERTY_DESTINATIONS,
    CreateTempoTransferRequest.JSON_PROPERTY_FAIL_ON_LOW_FEE,
    CreateTempoTransferRequest.JSON_PROPERTY_GAS_LIMIT,
    CreateTempoTransferRequest.JSON_PROPERTY_REPLACE_TX_BY_HASH,
    CreateTempoTransferRequest.JSON_PROPERTY_FEE_PAYER_ACCOUNT_ID,
    CreateTempoTransferRequest.JSON_PROPERTY_NONCE_STRATEGY,
    CreateTempoTransferRequest.JSON_PROPERTY_NONCE_LANE,
    CreateTempoTransferRequest.JSON_PROPERTY_MEMO
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class CreateTempoTransferRequest {
    public static final String JSON_PROPERTY_NOTE = "note";
    @jakarta.annotation.Nullable private String note;

    public static final String JSON_PROPERTY_EXTERNAL_TX_ID = "externalTxId";
    @jakarta.annotation.Nullable private String externalTxId;

    public static final String JSON_PROPERTY_FEE_CURRENCY = "feeCurrency";
    @jakarta.annotation.Nullable private String feeCurrency;

    public static final String JSON_PROPERTY_ASSET_ID = "assetId";
    @jakarta.annotation.Nonnull private String assetId;

    public static final String JSON_PROPERTY_SOURCE = "source";
    @jakarta.annotation.Nonnull private TempoTransferSource source;

    public static final String JSON_PROPERTY_DESTINATION = "destination";
    @jakarta.annotation.Nullable private TempoTransferDestination destination;

    public static final String JSON_PROPERTY_AMOUNT = "amount";
    @jakarta.annotation.Nullable private String amount;

    public static final String JSON_PROPERTY_TREAT_AS_GROSS_AMOUNT = "treatAsGrossAmount";
    @jakarta.annotation.Nullable private Boolean treatAsGrossAmount;

    /** The fee level to use, mutually exclusive with an explicit custom fee. */
    public enum FeeLevelEnum {
        LOW(String.valueOf("LOW")),

        MEDIUM(String.valueOf("MEDIUM")),

        HIGH(String.valueOf("HIGH"));

        private String value;

        FeeLevelEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static FeeLevelEnum fromValue(String value) {
            for (FeeLevelEnum b : FeeLevelEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_FEE_LEVEL = "feeLevel";
    @jakarta.annotation.Nullable private FeeLevelEnum feeLevel;

    public static final String JSON_PROPERTY_TRAVEL_RULE_MESSAGE = "travelRuleMessage";
    @jakarta.annotation.Nullable private String travelRuleMessage;

    public static final String JSON_PROPERTY_TRAVEL_RULE_MESSAGE_ID = "travelRuleMessageId";
    @jakarta.annotation.Nullable private String travelRuleMessageId;

    public static final String JSON_PROPERTY_USE_GASLESS = "useGasless";
    @jakarta.annotation.Nullable private Boolean useGasless;

    public static final String JSON_PROPERTY_CONFIGURATIONS = "configurations";
    @jakarta.annotation.Nullable private TransactionConfigurations configurations;

    public static final String JSON_PROPERTY_MAX_FEE_PER_GAS = "maxFeePerGas";
    @jakarta.annotation.Nullable private String maxFeePerGas;

    public static final String JSON_PROPERTY_MAX_PRIORITY_FEE_PER_GAS = "maxPriorityFeePerGas";
    @jakarta.annotation.Nullable private String maxPriorityFeePerGas;

    public static final String JSON_PROPERTY_DESTINATIONS = "destinations";
    @jakarta.annotation.Nullable private List<TempoTransferDestinationItem> destinations;

    public static final String JSON_PROPERTY_FAIL_ON_LOW_FEE = "failOnLowFee";
    @jakarta.annotation.Nullable private Boolean failOnLowFee;

    public static final String JSON_PROPERTY_GAS_LIMIT = "gasLimit";
    @jakarta.annotation.Nullable private String gasLimit;

    public static final String JSON_PROPERTY_REPLACE_TX_BY_HASH = "replaceTxByHash";
    @jakarta.annotation.Nullable private String replaceTxByHash;

    public static final String JSON_PROPERTY_FEE_PAYER_ACCOUNT_ID = "feePayerAccountId";
    @jakarta.annotation.Nullable private String feePayerAccountId;

    /**
     * Tempo&#39;s 2-dimensional nonce strategy: &#x60;SEQUENTIAL&#x60; runs under a single nonce
     * lane (lane 0); &#x60;USER_DEFINED_LANE&#x60; runs in parallel under a specified lane (1–16),
     * and requires &#x60;nonceLane&#x60;; &#x60;EXPIRING&#x60; marks the transaction with an expiry
     * of up to 5 minutes (Tempo-defined) and does not use &#x60;nonceLane&#x60;.
     */
    public enum NonceStrategyEnum {
        SEQUENTIAL(String.valueOf("SEQUENTIAL")),

        USER_DEFINED_LANE(String.valueOf("USER_DEFINED_LANE")),

        EXPIRING(String.valueOf("EXPIRING"));

        private String value;

        NonceStrategyEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static NonceStrategyEnum fromValue(String value) {
            for (NonceStrategyEnum b : NonceStrategyEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_NONCE_STRATEGY = "nonceStrategy";
    @jakarta.annotation.Nullable private NonceStrategyEnum nonceStrategy;

    public static final String JSON_PROPERTY_NONCE_LANE = "nonceLane";
    @jakarta.annotation.Nullable private Integer nonceLane;

    public static final String JSON_PROPERTY_MEMO = "memo";
    @jakarta.annotation.Nullable private String memo;

    public CreateTempoTransferRequest() {}

    @JsonCreator
    public CreateTempoTransferRequest(
            @JsonProperty(value = JSON_PROPERTY_ASSET_ID, required = true) String assetId,
            @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
                    TempoTransferSource source) {
        this.assetId = assetId;
        this.source = source;
    }

    public CreateTempoTransferRequest note(@jakarta.annotation.Nullable String note) {
        this.note = note;
        return this;
    }

    /**
     * A custom note that can be associated with the transaction.
     *
     * @return note
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NOTE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getNote() {
        return note;
    }

    @JsonProperty(JSON_PROPERTY_NOTE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNote(@jakarta.annotation.Nullable String note) {
        this.note = note;
    }

    public CreateTempoTransferRequest externalTxId(
            @jakarta.annotation.Nullable String externalTxId) {
        this.externalTxId = externalTxId;
        return this;
    }

    /**
     * Unique ID provided by the customer, used to identify the transaction.
     *
     * @return externalTxId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EXTERNAL_TX_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getExternalTxId() {
        return externalTxId;
    }

    @JsonProperty(JSON_PROPERTY_EXTERNAL_TX_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExternalTxId(@jakarta.annotation.Nullable String externalTxId) {
        this.externalTxId = externalTxId;
    }

    public CreateTempoTransferRequest feeCurrency(@jakarta.annotation.Nullable String feeCurrency) {
        this.feeCurrency = feeCurrency;
        return this;
    }

    /**
     * The asset ID used to pay the transaction fee, if different from assetId. Maps to
     * FeeParams.feeCurrency. Must be a valid fee token for &#x60;assetId&#x60; (e.g. a TIP-20 gas
     * token for the base asset); an invalid pairing surfaces as 400 INVALID_FEE_CURRENCY_PARAM.
     *
     * @return feeCurrency
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FEE_CURRENCY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getFeeCurrency() {
        return feeCurrency;
    }

    @JsonProperty(JSON_PROPERTY_FEE_CURRENCY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFeeCurrency(@jakarta.annotation.Nullable String feeCurrency) {
        this.feeCurrency = feeCurrency;
    }

    public CreateTempoTransferRequest assetId(@jakarta.annotation.Nonnull String assetId) {
        this.assetId = assetId;
        return this;
    }

    /**
     * The ID of the asset to transfer. Must be a non-deprecated asset supported on a Tempo-eligible
     * blockchain; an unknown, deprecated, or unsupported asset surfaces as 400 UNSUPPORTED_ASSET.
     *
     * @return assetId
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ASSET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getAssetId() {
        return assetId;
    }

    @JsonProperty(JSON_PROPERTY_ASSET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAssetId(@jakarta.annotation.Nonnull String assetId) {
        this.assetId = assetId;
    }

    public CreateTempoTransferRequest source(
            @jakarta.annotation.Nonnull TempoTransferSource source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_SOURCE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TempoTransferSource getSource() {
        return source;
    }

    @JsonProperty(JSON_PROPERTY_SOURCE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSource(@jakarta.annotation.Nonnull TempoTransferSource source) {
        this.source = source;
    }

    public CreateTempoTransferRequest destination(
            @jakarta.annotation.Nullable TempoTransferDestination destination) {
        this.destination = destination;
        return this;
    }

    /**
     * Get destination
     *
     * @return destination
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public TempoTransferDestination getDestination() {
        return destination;
    }

    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDestination(@jakarta.annotation.Nullable TempoTransferDestination destination) {
        this.destination = destination;
    }

    public CreateTempoTransferRequest amount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * The amount to transfer, as a numeric string. Required when &#x60;destination&#x60; is set;
     * must be omitted when &#x60;destinations&#x60; is set (each entry carries its own amount
     * instead).
     *
     * @return amount
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAmount() {
        return amount;
    }

    @JsonProperty(JSON_PROPERTY_AMOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAmount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
    }

    public CreateTempoTransferRequest treatAsGrossAmount(
            @jakarta.annotation.Nullable Boolean treatAsGrossAmount) {
        this.treatAsGrossAmount = treatAsGrossAmount;
        return this;
    }

    /**
     * If true, the specified amount includes the fee (fee is deducted from amount).
     *
     * @return treatAsGrossAmount
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TREAT_AS_GROSS_AMOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getTreatAsGrossAmount() {
        return treatAsGrossAmount;
    }

    @JsonProperty(JSON_PROPERTY_TREAT_AS_GROSS_AMOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTreatAsGrossAmount(@jakarta.annotation.Nullable Boolean treatAsGrossAmount) {
        this.treatAsGrossAmount = treatAsGrossAmount;
    }

    public CreateTempoTransferRequest feeLevel(@jakarta.annotation.Nullable FeeLevelEnum feeLevel) {
        this.feeLevel = feeLevel;
        return this;
    }

    /**
     * The fee level to use, mutually exclusive with an explicit custom fee.
     *
     * @return feeLevel
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FEE_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public FeeLevelEnum getFeeLevel() {
        return feeLevel;
    }

    @JsonProperty(JSON_PROPERTY_FEE_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFeeLevel(@jakarta.annotation.Nullable FeeLevelEnum feeLevel) {
        this.feeLevel = feeLevel;
    }

    public CreateTempoTransferRequest travelRuleMessage(
            @jakarta.annotation.Nullable String travelRuleMessage) {
        this.travelRuleMessage = travelRuleMessage;
        return this;
    }

    /**
     * Beta. An opaque travel-rule payload.
     *
     * @return travelRuleMessage
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRAVEL_RULE_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTravelRuleMessage() {
        return travelRuleMessage;
    }

    @JsonProperty(JSON_PROPERTY_TRAVEL_RULE_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTravelRuleMessage(@jakarta.annotation.Nullable String travelRuleMessage) {
        this.travelRuleMessage = travelRuleMessage;
    }

    public CreateTempoTransferRequest travelRuleMessageId(
            @jakarta.annotation.Nullable String travelRuleMessageId) {
        this.travelRuleMessageId = travelRuleMessageId;
        return this;
    }

    /**
     * Beta. An identifier of a TravelRule message, already sent to the TravelRule provider.
     *
     * @return travelRuleMessageId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRAVEL_RULE_MESSAGE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTravelRuleMessageId() {
        return travelRuleMessageId;
    }

    @JsonProperty(JSON_PROPERTY_TRAVEL_RULE_MESSAGE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTravelRuleMessageId(@jakarta.annotation.Nullable String travelRuleMessageId) {
        this.travelRuleMessageId = travelRuleMessageId;
    }

    public CreateTempoTransferRequest useGasless(@jakarta.annotation.Nullable Boolean useGasless) {
        this.useGasless = useGasless;
        return this;
    }

    /**
     * Opt in to fee-payer-sponsored (gasless) transfer.
     *
     * @return useGasless
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USE_GASLESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getUseGasless() {
        return useGasless;
    }

    @JsonProperty(JSON_PROPERTY_USE_GASLESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUseGasless(@jakarta.annotation.Nullable Boolean useGasless) {
        this.useGasless = useGasless;
    }

    public CreateTempoTransferRequest configurations(
            @jakarta.annotation.Nullable TransactionConfigurations configurations) {
        this.configurations = configurations;
        return this;
    }

    /**
     * Get configurations
     *
     * @return configurations
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONFIGURATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public TransactionConfigurations getConfigurations() {
        return configurations;
    }

    @JsonProperty(JSON_PROPERTY_CONFIGURATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setConfigurations(
            @jakarta.annotation.Nullable TransactionConfigurations configurations) {
        this.configurations = configurations;
    }

    public CreateTempoTransferRequest maxFeePerGas(
            @jakarta.annotation.Nullable String maxFeePerGas) {
        this.maxFeePerGas = maxFeePerGas;
        return this;
    }

    /**
     * The maximum total fee per gas the sender is willing to pay, in wei.
     *
     * @return maxFeePerGas
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_FEE_PER_GAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMaxFeePerGas() {
        return maxFeePerGas;
    }

    @JsonProperty(JSON_PROPERTY_MAX_FEE_PER_GAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxFeePerGas(@jakarta.annotation.Nullable String maxFeePerGas) {
        this.maxFeePerGas = maxFeePerGas;
    }

    public CreateTempoTransferRequest maxPriorityFeePerGas(
            @jakarta.annotation.Nullable String maxPriorityFeePerGas) {
        this.maxPriorityFeePerGas = maxPriorityFeePerGas;
        return this;
    }

    /**
     * The maximum priority fee (tip) per gas the sender is willing to pay, in wei.
     *
     * @return maxPriorityFeePerGas
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_PRIORITY_FEE_PER_GAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMaxPriorityFeePerGas() {
        return maxPriorityFeePerGas;
    }

    @JsonProperty(JSON_PROPERTY_MAX_PRIORITY_FEE_PER_GAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxPriorityFeePerGas(@jakarta.annotation.Nullable String maxPriorityFeePerGas) {
        this.maxPriorityFeePerGas = maxPriorityFeePerGas;
    }

    public CreateTempoTransferRequest destinations(
            @jakarta.annotation.Nullable List<TempoTransferDestinationItem> destinations) {
        this.destinations = destinations;
        return this;
    }

    public CreateTempoTransferRequest addDestinationsItem(
            TempoTransferDestinationItem destinationsItem) {
        if (this.destinations == null) {
            this.destinations = new ArrayList<>();
        }
        this.destinations.add(destinationsItem);
        return this;
    }

    /**
     * Multiple destinations for a single transfer. Mutually exclusive with &#x60;destination&#x60;.
     *
     * @return destinations
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESTINATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<TempoTransferDestinationItem> getDestinations() {
        return destinations;
    }

    @JsonProperty(JSON_PROPERTY_DESTINATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDestinations(
            @jakarta.annotation.Nullable List<TempoTransferDestinationItem> destinations) {
        this.destinations = destinations;
    }

    public CreateTempoTransferRequest failOnLowFee(
            @jakarta.annotation.Nullable Boolean failOnLowFee) {
        this.failOnLowFee = failOnLowFee;
        return this;
    }

    /**
     * Beta. If true, fail the transaction rather than sending it with a low fee.
     *
     * @return failOnLowFee
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FAIL_ON_LOW_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getFailOnLowFee() {
        return failOnLowFee;
    }

    @JsonProperty(JSON_PROPERTY_FAIL_ON_LOW_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFailOnLowFee(@jakarta.annotation.Nullable Boolean failOnLowFee) {
        this.failOnLowFee = failOnLowFee;
    }

    public CreateTempoTransferRequest gasLimit(@jakarta.annotation.Nullable String gasLimit) {
        this.gasLimit = gasLimit;
        return this;
    }

    /**
     * The gas limit for the transaction.
     *
     * @return gasLimit
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_GAS_LIMIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getGasLimit() {
        return gasLimit;
    }

    @JsonProperty(JSON_PROPERTY_GAS_LIMIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGasLimit(@jakarta.annotation.Nullable String gasLimit) {
        this.gasLimit = gasLimit;
    }

    public CreateTempoTransferRequest replaceTxByHash(
            @jakarta.annotation.Nullable String replaceTxByHash) {
        this.replaceTxByHash = replaceTxByHash;
        return this;
    }

    /**
     * Beta. The hash of the EVM transaction to replace (RBF).
     *
     * @return replaceTxByHash
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REPLACE_TX_BY_HASH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getReplaceTxByHash() {
        return replaceTxByHash;
    }

    @JsonProperty(JSON_PROPERTY_REPLACE_TX_BY_HASH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReplaceTxByHash(@jakarta.annotation.Nullable String replaceTxByHash) {
        this.replaceTxByHash = replaceTxByHash;
    }

    public CreateTempoTransferRequest feePayerAccountId(
            @jakarta.annotation.Nullable String feePayerAccountId) {
        this.feePayerAccountId = feePayerAccountId;
        return this;
    }

    /**
     * Vault account ID of the fee payer sponsoring this transfer.
     *
     * @return feePayerAccountId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FEE_PAYER_ACCOUNT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getFeePayerAccountId() {
        return feePayerAccountId;
    }

    @JsonProperty(JSON_PROPERTY_FEE_PAYER_ACCOUNT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFeePayerAccountId(@jakarta.annotation.Nullable String feePayerAccountId) {
        this.feePayerAccountId = feePayerAccountId;
    }

    public CreateTempoTransferRequest nonceStrategy(
            @jakarta.annotation.Nullable NonceStrategyEnum nonceStrategy) {
        this.nonceStrategy = nonceStrategy;
        return this;
    }

    /**
     * Tempo&#39;s 2-dimensional nonce strategy: &#x60;SEQUENTIAL&#x60; runs under a single nonce
     * lane (lane 0); &#x60;USER_DEFINED_LANE&#x60; runs in parallel under a specified lane (1–16),
     * and requires &#x60;nonceLane&#x60;; &#x60;EXPIRING&#x60; marks the transaction with an expiry
     * of up to 5 minutes (Tempo-defined) and does not use &#x60;nonceLane&#x60;.
     *
     * @return nonceStrategy
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NONCE_STRATEGY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public NonceStrategyEnum getNonceStrategy() {
        return nonceStrategy;
    }

    @JsonProperty(JSON_PROPERTY_NONCE_STRATEGY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNonceStrategy(@jakarta.annotation.Nullable NonceStrategyEnum nonceStrategy) {
        this.nonceStrategy = nonceStrategy;
    }

    public CreateTempoTransferRequest nonceLane(@jakarta.annotation.Nullable Integer nonceLane) {
        this.nonceLane = nonceLane;
        return this;
    }

    /**
     * The nonce lane to use, 1–16. Required and only meaningful when nonceStrategy is
     * USER_DEFINED_LANE; not used for SEQUENTIAL or EXPIRING. minimum: 1 maximum: 16
     *
     * @return nonceLane
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NONCE_LANE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getNonceLane() {
        return nonceLane;
    }

    @JsonProperty(JSON_PROPERTY_NONCE_LANE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNonceLane(@jakarta.annotation.Nullable Integer nonceLane) {
        this.nonceLane = nonceLane;
    }

    public CreateTempoTransferRequest memo(@jakarta.annotation.Nullable String memo) {
        this.memo = memo;
        return this;
    }

    /**
     * Beta. Tempo TIP-20 memo (max 32 bytes).
     *
     * @return memo
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MEMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMemo() {
        return memo;
    }

    @JsonProperty(JSON_PROPERTY_MEMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMemo(@jakarta.annotation.Nullable String memo) {
        this.memo = memo;
    }

    /** Return true if this CreateTempoTransferRequest object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateTempoTransferRequest createTempoTransferRequest = (CreateTempoTransferRequest) o;
        return Objects.equals(this.note, createTempoTransferRequest.note)
                && Objects.equals(this.externalTxId, createTempoTransferRequest.externalTxId)
                && Objects.equals(this.feeCurrency, createTempoTransferRequest.feeCurrency)
                && Objects.equals(this.assetId, createTempoTransferRequest.assetId)
                && Objects.equals(this.source, createTempoTransferRequest.source)
                && Objects.equals(this.destination, createTempoTransferRequest.destination)
                && Objects.equals(this.amount, createTempoTransferRequest.amount)
                && Objects.equals(
                        this.treatAsGrossAmount, createTempoTransferRequest.treatAsGrossAmount)
                && Objects.equals(this.feeLevel, createTempoTransferRequest.feeLevel)
                && Objects.equals(
                        this.travelRuleMessage, createTempoTransferRequest.travelRuleMessage)
                && Objects.equals(
                        this.travelRuleMessageId, createTempoTransferRequest.travelRuleMessageId)
                && Objects.equals(this.useGasless, createTempoTransferRequest.useGasless)
                && Objects.equals(this.configurations, createTempoTransferRequest.configurations)
                && Objects.equals(this.maxFeePerGas, createTempoTransferRequest.maxFeePerGas)
                && Objects.equals(
                        this.maxPriorityFeePerGas, createTempoTransferRequest.maxPriorityFeePerGas)
                && Objects.equals(this.destinations, createTempoTransferRequest.destinations)
                && Objects.equals(this.failOnLowFee, createTempoTransferRequest.failOnLowFee)
                && Objects.equals(this.gasLimit, createTempoTransferRequest.gasLimit)
                && Objects.equals(this.replaceTxByHash, createTempoTransferRequest.replaceTxByHash)
                && Objects.equals(
                        this.feePayerAccountId, createTempoTransferRequest.feePayerAccountId)
                && Objects.equals(this.nonceStrategy, createTempoTransferRequest.nonceStrategy)
                && Objects.equals(this.nonceLane, createTempoTransferRequest.nonceLane)
                && Objects.equals(this.memo, createTempoTransferRequest.memo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                note,
                externalTxId,
                feeCurrency,
                assetId,
                source,
                destination,
                amount,
                treatAsGrossAmount,
                feeLevel,
                travelRuleMessage,
                travelRuleMessageId,
                useGasless,
                configurations,
                maxFeePerGas,
                maxPriorityFeePerGas,
                destinations,
                failOnLowFee,
                gasLimit,
                replaceTxByHash,
                feePayerAccountId,
                nonceStrategy,
                nonceLane,
                memo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateTempoTransferRequest {\n");
        sb.append("    note: ").append(toIndentedString(note)).append("\n");
        sb.append("    externalTxId: ").append(toIndentedString(externalTxId)).append("\n");
        sb.append("    feeCurrency: ").append(toIndentedString(feeCurrency)).append("\n");
        sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    treatAsGrossAmount: ")
                .append(toIndentedString(treatAsGrossAmount))
                .append("\n");
        sb.append("    feeLevel: ").append(toIndentedString(feeLevel)).append("\n");
        sb.append("    travelRuleMessage: ")
                .append(toIndentedString(travelRuleMessage))
                .append("\n");
        sb.append("    travelRuleMessageId: ")
                .append(toIndentedString(travelRuleMessageId))
                .append("\n");
        sb.append("    useGasless: ").append(toIndentedString(useGasless)).append("\n");
        sb.append("    configurations: ").append(toIndentedString(configurations)).append("\n");
        sb.append("    maxFeePerGas: ").append(toIndentedString(maxFeePerGas)).append("\n");
        sb.append("    maxPriorityFeePerGas: ")
                .append(toIndentedString(maxPriorityFeePerGas))
                .append("\n");
        sb.append("    destinations: ").append(toIndentedString(destinations)).append("\n");
        sb.append("    failOnLowFee: ").append(toIndentedString(failOnLowFee)).append("\n");
        sb.append("    gasLimit: ").append(toIndentedString(gasLimit)).append("\n");
        sb.append("    replaceTxByHash: ").append(toIndentedString(replaceTxByHash)).append("\n");
        sb.append("    feePayerAccountId: ")
                .append(toIndentedString(feePayerAccountId))
                .append("\n");
        sb.append("    nonceStrategy: ").append(toIndentedString(nonceStrategy)).append("\n");
        sb.append("    nonceLane: ").append(toIndentedString(nonceLane)).append("\n");
        sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `note` to the URL query string
        if (getNote() != null) {
            joiner.add(
                    String.format(
                            "%snote%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getNote()))));
        }

        // add `externalTxId` to the URL query string
        if (getExternalTxId() != null) {
            joiner.add(
                    String.format(
                            "%sexternalTxId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getExternalTxId()))));
        }

        // add `feeCurrency` to the URL query string
        if (getFeeCurrency() != null) {
            joiner.add(
                    String.format(
                            "%sfeeCurrency%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getFeeCurrency()))));
        }

        // add `assetId` to the URL query string
        if (getAssetId() != null) {
            joiner.add(
                    String.format(
                            "%sassetId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getAssetId()))));
        }

        // add `source` to the URL query string
        if (getSource() != null) {
            joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
        }

        // add `destination` to the URL query string
        if (getDestination() != null) {
            joiner.add(getDestination().toUrlQueryString(prefix + "destination" + suffix));
        }

        // add `amount` to the URL query string
        if (getAmount() != null) {
            joiner.add(
                    String.format(
                            "%samount%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
        }

        // add `treatAsGrossAmount` to the URL query string
        if (getTreatAsGrossAmount() != null) {
            joiner.add(
                    String.format(
                            "%streatAsGrossAmount%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getTreatAsGrossAmount()))));
        }

        // add `feeLevel` to the URL query string
        if (getFeeLevel() != null) {
            joiner.add(
                    String.format(
                            "%sfeeLevel%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getFeeLevel()))));
        }

        // add `travelRuleMessage` to the URL query string
        if (getTravelRuleMessage() != null) {
            joiner.add(
                    String.format(
                            "%stravelRuleMessage%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getTravelRuleMessage()))));
        }

        // add `travelRuleMessageId` to the URL query string
        if (getTravelRuleMessageId() != null) {
            joiner.add(
                    String.format(
                            "%stravelRuleMessageId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(
                                    ApiClient.valueToString(getTravelRuleMessageId()))));
        }

        // add `useGasless` to the URL query string
        if (getUseGasless() != null) {
            joiner.add(
                    String.format(
                            "%suseGasless%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getUseGasless()))));
        }

        // add `configurations` to the URL query string
        if (getConfigurations() != null) {
            joiner.add(getConfigurations().toUrlQueryString(prefix + "configurations" + suffix));
        }

        // add `maxFeePerGas` to the URL query string
        if (getMaxFeePerGas() != null) {
            joiner.add(
                    String.format(
                            "%smaxFeePerGas%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getMaxFeePerGas()))));
        }

        // add `maxPriorityFeePerGas` to the URL query string
        if (getMaxPriorityFeePerGas() != null) {
            joiner.add(
                    String.format(
                            "%smaxPriorityFeePerGas%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(
                                    ApiClient.valueToString(getMaxPriorityFeePerGas()))));
        }

        // add `destinations` to the URL query string
        if (getDestinations() != null) {
            for (int i = 0; i < getDestinations().size(); i++) {
                if (getDestinations().get(i) != null) {
                    joiner.add(
                            getDestinations()
                                    .get(i)
                                    .toUrlQueryString(
                                            String.format(
                                                    "%sdestinations%s%s",
                                                    prefix,
                                                    suffix,
                                                    "".equals(suffix)
                                                            ? ""
                                                            : String.format(
                                                                    "%s%d%s",
                                                                    containerPrefix,
                                                                    i,
                                                                    containerSuffix))));
                }
            }
        }

        // add `failOnLowFee` to the URL query string
        if (getFailOnLowFee() != null) {
            joiner.add(
                    String.format(
                            "%sfailOnLowFee%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getFailOnLowFee()))));
        }

        // add `gasLimit` to the URL query string
        if (getGasLimit() != null) {
            joiner.add(
                    String.format(
                            "%sgasLimit%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getGasLimit()))));
        }

        // add `replaceTxByHash` to the URL query string
        if (getReplaceTxByHash() != null) {
            joiner.add(
                    String.format(
                            "%sreplaceTxByHash%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getReplaceTxByHash()))));
        }

        // add `feePayerAccountId` to the URL query string
        if (getFeePayerAccountId() != null) {
            joiner.add(
                    String.format(
                            "%sfeePayerAccountId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getFeePayerAccountId()))));
        }

        // add `nonceStrategy` to the URL query string
        if (getNonceStrategy() != null) {
            joiner.add(
                    String.format(
                            "%snonceStrategy%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getNonceStrategy()))));
        }

        // add `nonceLane` to the URL query string
        if (getNonceLane() != null) {
            joiner.add(
                    String.format(
                            "%snonceLane%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getNonceLane()))));
        }

        // add `memo` to the URL query string
        if (getMemo() != null) {
            joiner.add(
                    String.format(
                            "%smemo%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getMemo()))));
        }

        return joiner.toString();
    }
}
