/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fireblocks.sdk.ApiClient;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Relay (meta-transaction) details. Returned only for meta-transactions (&#x60;isMetaTx&#x60; is
 * &#x60;true&#x60;). For meta-transactions the deprecated top-level &#x60;fee&#x60; field is
 * omitted; use &#x60;feeInfo&#x60; instead.
 */
@JsonPropertyOrder({
    GaslessInfo.JSON_PROPERTY_IS_META_TX,
    GaslessInfo.JSON_PROPERTY_RELAY_TENANT_ID,
    GaslessInfo.JSON_PROPERTY_RELAY_TENANT_NAME,
    GaslessInfo.JSON_PROPERTY_RELAY_VAULT_ACCOUNT_ID
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class GaslessInfo {
    public static final String JSON_PROPERTY_IS_META_TX = "isMetaTx";
    @jakarta.annotation.Nullable private Boolean isMetaTx;

    public static final String JSON_PROPERTY_RELAY_TENANT_ID = "relayTenantId";
    @jakarta.annotation.Nullable private String relayTenantId;

    public static final String JSON_PROPERTY_RELAY_TENANT_NAME = "relayTenantName";
    @jakarta.annotation.Nullable private String relayTenantName;

    public static final String JSON_PROPERTY_RELAY_VAULT_ACCOUNT_ID = "relayVaultAccountId";
    @jakarta.annotation.Nullable private String relayVaultAccountId;

    public GaslessInfo() {}

    public GaslessInfo isMetaTx(@jakarta.annotation.Nullable Boolean isMetaTx) {
        this.isMetaTx = isMetaTx;
        return this;
    }

    /**
     * Indicates the transaction is a meta-transaction (gas paid by a relay tenant).
     *
     * @return isMetaTx
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_META_TX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getIsMetaTx() {
        return isMetaTx;
    }

    @JsonProperty(JSON_PROPERTY_IS_META_TX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsMetaTx(@jakarta.annotation.Nullable Boolean isMetaTx) {
        this.isMetaTx = isMetaTx;
    }

    public GaslessInfo relayTenantId(@jakarta.annotation.Nullable String relayTenantId) {
        this.relayTenantId = relayTenantId;
        return this;
    }

    /**
     * The tenant ID of the relay that sponsors the gas for the meta-transaction.
     *
     * @return relayTenantId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RELAY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getRelayTenantId() {
        return relayTenantId;
    }

    @JsonProperty(JSON_PROPERTY_RELAY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRelayTenantId(@jakarta.annotation.Nullable String relayTenantId) {
        this.relayTenantId = relayTenantId;
    }

    public GaslessInfo relayTenantName(@jakarta.annotation.Nullable String relayTenantName) {
        this.relayTenantName = relayTenantName;
        return this;
    }

    /**
     * The tenant name of the relay that sponsors the gas for the meta-transaction.
     *
     * @return relayTenantName
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RELAY_TENANT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getRelayTenantName() {
        return relayTenantName;
    }

    @JsonProperty(JSON_PROPERTY_RELAY_TENANT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRelayTenantName(@jakarta.annotation.Nullable String relayTenantName) {
        this.relayTenantName = relayTenantName;
    }

    public GaslessInfo relayVaultAccountId(
            @jakarta.annotation.Nullable String relayVaultAccountId) {
        this.relayVaultAccountId = relayVaultAccountId;
        return this;
    }

    /**
     * The vault account ID of the relay that sponsors the gas for the meta-transaction.
     *
     * @return relayVaultAccountId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RELAY_VAULT_ACCOUNT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getRelayVaultAccountId() {
        return relayVaultAccountId;
    }

    @JsonProperty(JSON_PROPERTY_RELAY_VAULT_ACCOUNT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRelayVaultAccountId(@jakarta.annotation.Nullable String relayVaultAccountId) {
        this.relayVaultAccountId = relayVaultAccountId;
    }

    /** Return true if this GaslessInfo object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GaslessInfo gaslessInfo = (GaslessInfo) o;
        return Objects.equals(this.isMetaTx, gaslessInfo.isMetaTx)
                && Objects.equals(this.relayTenantId, gaslessInfo.relayTenantId)
                && Objects.equals(this.relayTenantName, gaslessInfo.relayTenantName)
                && Objects.equals(this.relayVaultAccountId, gaslessInfo.relayVaultAccountId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isMetaTx, relayTenantId, relayTenantName, relayVaultAccountId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GaslessInfo {\n");
        sb.append("    isMetaTx: ").append(toIndentedString(isMetaTx)).append("\n");
        sb.append("    relayTenantId: ").append(toIndentedString(relayTenantId)).append("\n");
        sb.append("    relayTenantName: ").append(toIndentedString(relayTenantName)).append("\n");
        sb.append("    relayVaultAccountId: ")
                .append(toIndentedString(relayVaultAccountId))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `isMetaTx` to the URL query string
        if (getIsMetaTx() != null) {
            joiner.add(
                    String.format(
                            "%sisMetaTx%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getIsMetaTx()))));
        }

        // add `relayTenantId` to the URL query string
        if (getRelayTenantId() != null) {
            joiner.add(
                    String.format(
                            "%srelayTenantId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getRelayTenantId()))));
        }

        // add `relayTenantName` to the URL query string
        if (getRelayTenantName() != null) {
            joiner.add(
                    String.format(
                            "%srelayTenantName%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getRelayTenantName()))));
        }

        // add `relayVaultAccountId` to the URL query string
        if (getRelayVaultAccountId() != null) {
            joiner.add(
                    String.format(
                            "%srelayVaultAccountId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(
                                    ApiClient.valueToString(getRelayVaultAccountId()))));
        }

        return joiner.toString();
    }
}
