/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fireblocks.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fireblocks.sdk.model.NetworkConnectionRoutingPolicy;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fireblocks.sdk.JSON;


/**
 * NetworkConnection
 */
@JsonPropertyOrder({
  NetworkConnection.JSON_PROPERTY_LOCAL_NETWORK_ID,
  NetworkConnection.JSON_PROPERTY_REMOTE_NETWORK_ID,
  NetworkConnection.JSON_PROPERTY_ROUTING_POLICY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NetworkConnection {
  public static final String JSON_PROPERTY_LOCAL_NETWORK_ID = "localNetworkId";
  private String localNetworkId;

  public static final String JSON_PROPERTY_REMOTE_NETWORK_ID = "remoteNetworkId";
  private String remoteNetworkId;

  public static final String JSON_PROPERTY_ROUTING_POLICY = "routingPolicy";
  private NetworkConnectionRoutingPolicy routingPolicy;

  public NetworkConnection() { 
  }

  public NetworkConnection localNetworkId(String localNetworkId) {
    this.localNetworkId = localNetworkId;
    return this;
  }

   /**
   * The network ID of the profile trying to create the connection.
   * @return localNetworkId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCAL_NETWORK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLocalNetworkId() {
    return localNetworkId;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_NETWORK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocalNetworkId(String localNetworkId) {
    this.localNetworkId = localNetworkId;
  }


  public NetworkConnection remoteNetworkId(String remoteNetworkId) {
    this.remoteNetworkId = remoteNetworkId;
    return this;
  }

   /**
   * The network ID the profile is attempting to connect to.
   * @return remoteNetworkId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REMOTE_NETWORK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRemoteNetworkId() {
    return remoteNetworkId;
  }


  @JsonProperty(JSON_PROPERTY_REMOTE_NETWORK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemoteNetworkId(String remoteNetworkId) {
    this.remoteNetworkId = remoteNetworkId;
  }


  public NetworkConnection routingPolicy(NetworkConnectionRoutingPolicy routingPolicy) {
    this.routingPolicy = routingPolicy;
    return this;
  }

   /**
   * Get routingPolicy
   * @return routingPolicy
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTING_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NetworkConnectionRoutingPolicy getRoutingPolicy() {
    return routingPolicy;
  }


  @JsonProperty(JSON_PROPERTY_ROUTING_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutingPolicy(NetworkConnectionRoutingPolicy routingPolicy) {
    this.routingPolicy = routingPolicy;
  }


  /**
   * Return true if this NetworkConnection object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkConnection networkConnection = (NetworkConnection) o;
    return Objects.equals(this.localNetworkId, networkConnection.localNetworkId) &&
        Objects.equals(this.remoteNetworkId, networkConnection.remoteNetworkId) &&
        Objects.equals(this.routingPolicy, networkConnection.routingPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localNetworkId, remoteNetworkId, routingPolicy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkConnection {\n");
    sb.append("    localNetworkId: ").append(toIndentedString(localNetworkId)).append("\n");
    sb.append("    remoteNetworkId: ").append(toIndentedString(remoteNetworkId)).append("\n");
    sb.append("    routingPolicy: ").append(toIndentedString(routingPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

