/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/** OffersResponse */
@JsonPropertyOrder({OffersResponse.JSON_PROPERTY_OFFERS, OffersResponse.JSON_PROPERTY_ERRORS})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class OffersResponse {
    public static final String JSON_PROPERTY_OFFERS = "offers";
    @jakarta.annotation.Nonnull private List<Offer> offers;

    public static final String JSON_PROPERTY_ERRORS = "errors";
    @jakarta.annotation.Nonnull private List<ScopeItemFailure> errors;

    public OffersResponse() {}

    @JsonCreator
    public OffersResponse(
            @JsonProperty(value = JSON_PROPERTY_OFFERS, required = true) List<Offer> offers,
            @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
                    List<ScopeItemFailure> errors) {
        this.offers = offers;
        this.errors = errors;
    }

    public OffersResponse offers(@jakarta.annotation.Nonnull List<Offer> offers) {
        this.offers = offers;
        return this;
    }

    public OffersResponse addOffersItem(Offer offersItem) {
        if (this.offers == null) {
            this.offers = new ArrayList<>();
        }
        this.offers.add(offersItem);
        return this;
    }

    /**
     * List of offers returned for the requested asset pair.
     *
     * @return offers
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_OFFERS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<Offer> getOffers() {
        return offers;
    }

    @JsonProperty(JSON_PROPERTY_OFFERS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOffers(@jakarta.annotation.Nonnull List<Offer> offers) {
        this.offers = offers;
    }

    public OffersResponse errors(@jakarta.annotation.Nonnull List<ScopeItemFailure> errors) {
        this.errors = errors;
        return this;
    }

    public OffersResponse addErrorsItem(ScopeItemFailure errorsItem) {
        if (this.errors == null) {
            this.errors = new ArrayList<>();
        }
        this.errors.add(errorsItem);
        return this;
    }

    /**
     * Partial failures encountered while requesting offers. Empty when all offer requests succeed.
     *
     * @return errors
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ERRORS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<ScopeItemFailure> getErrors() {
        return errors;
    }

    @JsonProperty(JSON_PROPERTY_ERRORS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setErrors(@jakarta.annotation.Nonnull List<ScopeItemFailure> errors) {
        this.errors = errors;
    }

    /** Return true if this OffersResponse object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OffersResponse offersResponse = (OffersResponse) o;
        return Objects.equals(this.offers, offersResponse.offers)
                && Objects.equals(this.errors, offersResponse.errors);
    }

    @Override
    public int hashCode() {
        return Objects.hash(offers, errors);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OffersResponse {\n");
        sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
        sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `offers` to the URL query string
        if (getOffers() != null) {
            for (int i = 0; i < getOffers().size(); i++) {
                if (getOffers().get(i) != null) {
                    joiner.add(
                            getOffers()
                                    .get(i)
                                    .toUrlQueryString(
                                            String.format(
                                                    "%soffers%s%s",
                                                    prefix,
                                                    suffix,
                                                    "".equals(suffix)
                                                            ? ""
                                                            : String.format(
                                                                    "%s%d%s",
                                                                    containerPrefix,
                                                                    i,
                                                                    containerSuffix))));
                }
            }
        }

        // add `errors` to the URL query string
        if (getErrors() != null) {
            for (int i = 0; i < getErrors().size(); i++) {
                if (getErrors().get(i) != null) {
                    joiner.add(
                            getErrors()
                                    .get(i)
                                    .toUrlQueryString(
                                            String.format(
                                                    "%serrors%s%s",
                                                    prefix,
                                                    suffix,
                                                    "".equals(suffix)
                                                            ? ""
                                                            : String.format(
                                                                    "%s%d%s",
                                                                    containerPrefix,
                                                                    i,
                                                                    containerSuffix))));
                }
            }
        }

        return joiner.toString();
    }
}
