/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fireblocks.sdk.ApiClient;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/** OnchainTransaction */
@JsonPropertyOrder({
    OnchainTransaction.JSON_PROPERTY_ID,
    OnchainTransaction.JSON_PROPERTY_BASE_ASSET_ID,
    OnchainTransaction.JSON_PROPERTY_BLOCK_HASH,
    OnchainTransaction.JSON_PROPERTY_BLOCK_NUMBER,
    OnchainTransaction.JSON_PROPERTY_BLOCK_TIMESTAMP,
    OnchainTransaction.JSON_PROPERTY_CHAIN_ID,
    OnchainTransaction.JSON_PROPERTY_CONTRACT_ADDRESS,
    OnchainTransaction.JSON_PROPERTY_CUMULATIVE_GAS_USED,
    OnchainTransaction.JSON_PROPERTY_DECODED_LOGS,
    OnchainTransaction.JSON_PROPERTY_EFFECTIVE_GAS_PRICE,
    OnchainTransaction.JSON_PROPERTY_FROM_ADDRESS,
    OnchainTransaction.JSON_PROPERTY_GAS_USED,
    OnchainTransaction.JSON_PROPERTY_STATUS,
    OnchainTransaction.JSON_PROPERTY_TO_ADDRESS,
    OnchainTransaction.JSON_PROPERTY_TRANSACTION_HASH,
    OnchainTransaction.JSON_PROPERTY_TRANSACTION_INDEX,
    OnchainTransaction.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class OnchainTransaction {
    public static final String JSON_PROPERTY_ID = "id";
    @jakarta.annotation.Nonnull private UUID id;

    public static final String JSON_PROPERTY_BASE_ASSET_ID = "baseAssetId";
    @jakarta.annotation.Nonnull private String baseAssetId;

    public static final String JSON_PROPERTY_BLOCK_HASH = "blockHash";
    @jakarta.annotation.Nonnull private String blockHash;

    public static final String JSON_PROPERTY_BLOCK_NUMBER = "blockNumber";
    @jakarta.annotation.Nonnull private Integer blockNumber;

    public static final String JSON_PROPERTY_BLOCK_TIMESTAMP = "blockTimestamp";
    @jakarta.annotation.Nonnull private OffsetDateTime blockTimestamp;

    public static final String JSON_PROPERTY_CHAIN_ID = "chainId";
    @jakarta.annotation.Nonnull private Integer chainId;

    public static final String JSON_PROPERTY_CONTRACT_ADDRESS = "contractAddress";
    @jakarta.annotation.Nullable private String contractAddress;

    public static final String JSON_PROPERTY_CUMULATIVE_GAS_USED = "cumulativeGasUsed";
    @jakarta.annotation.Nonnull private String cumulativeGasUsed;

    public static final String JSON_PROPERTY_DECODED_LOGS = "decodedLogs";
    @jakarta.annotation.Nullable private DecodedLog decodedLogs;

    public static final String JSON_PROPERTY_EFFECTIVE_GAS_PRICE = "effectiveGasPrice";
    @jakarta.annotation.Nonnull private String effectiveGasPrice;

    public static final String JSON_PROPERTY_FROM_ADDRESS = "fromAddress";
    @jakarta.annotation.Nonnull private String fromAddress;

    public static final String JSON_PROPERTY_GAS_USED = "gasUsed";
    @jakarta.annotation.Nonnull private String gasUsed;

    public static final String JSON_PROPERTY_STATUS = "status";
    @jakarta.annotation.Nonnull private String status;

    public static final String JSON_PROPERTY_TO_ADDRESS = "toAddress";
    @jakarta.annotation.Nullable private String toAddress;

    public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
    @jakarta.annotation.Nonnull private String transactionHash;

    public static final String JSON_PROPERTY_TRANSACTION_INDEX = "transactionIndex";
    @jakarta.annotation.Nonnull private String transactionIndex;

    public static final String JSON_PROPERTY_TYPE = "type";
    @jakarta.annotation.Nonnull private String type;

    public OnchainTransaction() {}

    @JsonCreator
    public OnchainTransaction(
            @JsonProperty(value = JSON_PROPERTY_ID, required = true) UUID id,
            @JsonProperty(value = JSON_PROPERTY_BASE_ASSET_ID, required = true) String baseAssetId,
            @JsonProperty(value = JSON_PROPERTY_BLOCK_HASH, required = true) String blockHash,
            @JsonProperty(value = JSON_PROPERTY_BLOCK_NUMBER, required = true) Integer blockNumber,
            @JsonProperty(value = JSON_PROPERTY_BLOCK_TIMESTAMP, required = true)
                    OffsetDateTime blockTimestamp,
            @JsonProperty(value = JSON_PROPERTY_CHAIN_ID, required = true) Integer chainId,
            @JsonProperty(value = JSON_PROPERTY_CUMULATIVE_GAS_USED, required = true)
                    String cumulativeGasUsed,
            @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_GAS_PRICE, required = true)
                    String effectiveGasPrice,
            @JsonProperty(value = JSON_PROPERTY_FROM_ADDRESS, required = true) String fromAddress,
            @JsonProperty(value = JSON_PROPERTY_GAS_USED, required = true) String gasUsed,
            @JsonProperty(value = JSON_PROPERTY_STATUS, required = true) String status,
            @JsonProperty(value = JSON_PROPERTY_TRANSACTION_HASH, required = true)
                    String transactionHash,
            @JsonProperty(value = JSON_PROPERTY_TRANSACTION_INDEX, required = true)
                    String transactionIndex,
            @JsonProperty(value = JSON_PROPERTY_TYPE, required = true) String type) {
        this.id = id;
        this.baseAssetId = baseAssetId;
        this.blockHash = blockHash;
        this.blockNumber = blockNumber;
        this.blockTimestamp = blockTimestamp;
        this.chainId = chainId;
        this.cumulativeGasUsed = cumulativeGasUsed;
        this.effectiveGasPrice = effectiveGasPrice;
        this.fromAddress = fromAddress;
        this.gasUsed = gasUsed;
        this.status = status;
        this.transactionHash = transactionHash;
        this.transactionIndex = transactionIndex;
        this.type = type;
    }

    public OnchainTransaction id(@jakarta.annotation.Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Unique identifier for the transaction
     *
     * @return id
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(@jakarta.annotation.Nonnull UUID id) {
        this.id = id;
    }

    public OnchainTransaction baseAssetId(@jakarta.annotation.Nonnull String baseAssetId) {
        this.baseAssetId = baseAssetId;
        return this;
    }

    /**
     * The blockchain base asset identifier
     *
     * @return baseAssetId
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_BASE_ASSET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getBaseAssetId() {
        return baseAssetId;
    }

    @JsonProperty(JSON_PROPERTY_BASE_ASSET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBaseAssetId(@jakarta.annotation.Nonnull String baseAssetId) {
        this.baseAssetId = baseAssetId;
    }

    public OnchainTransaction blockHash(@jakarta.annotation.Nonnull String blockHash) {
        this.blockHash = blockHash;
        return this;
    }

    /**
     * Hash of the block containing this transaction
     *
     * @return blockHash
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_BLOCK_HASH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getBlockHash() {
        return blockHash;
    }

    @JsonProperty(JSON_PROPERTY_BLOCK_HASH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBlockHash(@jakarta.annotation.Nonnull String blockHash) {
        this.blockHash = blockHash;
    }

    public OnchainTransaction blockNumber(@jakarta.annotation.Nonnull Integer blockNumber) {
        this.blockNumber = blockNumber;
        return this;
    }

    /**
     * Block number containing this transaction
     *
     * @return blockNumber
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_BLOCK_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getBlockNumber() {
        return blockNumber;
    }

    @JsonProperty(JSON_PROPERTY_BLOCK_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBlockNumber(@jakarta.annotation.Nonnull Integer blockNumber) {
        this.blockNumber = blockNumber;
    }

    public OnchainTransaction blockTimestamp(
            @jakarta.annotation.Nonnull OffsetDateTime blockTimestamp) {
        this.blockTimestamp = blockTimestamp;
        return this;
    }

    /**
     * Timestamp when the block was mined
     *
     * @return blockTimestamp
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_BLOCK_TIMESTAMP)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public OffsetDateTime getBlockTimestamp() {
        return blockTimestamp;
    }

    @JsonProperty(JSON_PROPERTY_BLOCK_TIMESTAMP)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBlockTimestamp(@jakarta.annotation.Nonnull OffsetDateTime blockTimestamp) {
        this.blockTimestamp = blockTimestamp;
    }

    public OnchainTransaction chainId(@jakarta.annotation.Nonnull Integer chainId) {
        this.chainId = chainId;
        return this;
    }

    /**
     * Chain ID of the blockchain
     *
     * @return chainId
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_CHAIN_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getChainId() {
        return chainId;
    }

    @JsonProperty(JSON_PROPERTY_CHAIN_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setChainId(@jakarta.annotation.Nonnull Integer chainId) {
        this.chainId = chainId;
    }

    public OnchainTransaction contractAddress(@jakarta.annotation.Nullable String contractAddress) {
        this.contractAddress = contractAddress;
        return this;
    }

    /**
     * Contract address if this is a contract transaction
     *
     * @return contractAddress
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getContractAddress() {
        return contractAddress;
    }

    @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setContractAddress(@jakarta.annotation.Nullable String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public OnchainTransaction cumulativeGasUsed(
            @jakarta.annotation.Nonnull String cumulativeGasUsed) {
        this.cumulativeGasUsed = cumulativeGasUsed;
        return this;
    }

    /**
     * Cumulative gas used in the block up to this transaction
     *
     * @return cumulativeGasUsed
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_CUMULATIVE_GAS_USED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getCumulativeGasUsed() {
        return cumulativeGasUsed;
    }

    @JsonProperty(JSON_PROPERTY_CUMULATIVE_GAS_USED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCumulativeGasUsed(@jakarta.annotation.Nonnull String cumulativeGasUsed) {
        this.cumulativeGasUsed = cumulativeGasUsed;
    }

    public OnchainTransaction decodedLogs(@jakarta.annotation.Nullable DecodedLog decodedLogs) {
        this.decodedLogs = decodedLogs;
        return this;
    }

    /**
     * Get decodedLogs
     *
     * @return decodedLogs
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DECODED_LOGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public DecodedLog getDecodedLogs() {
        return decodedLogs;
    }

    @JsonProperty(JSON_PROPERTY_DECODED_LOGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDecodedLogs(@jakarta.annotation.Nullable DecodedLog decodedLogs) {
        this.decodedLogs = decodedLogs;
    }

    public OnchainTransaction effectiveGasPrice(
            @jakarta.annotation.Nonnull String effectiveGasPrice) {
        this.effectiveGasPrice = effectiveGasPrice;
        return this;
    }

    /**
     * Effective gas price paid for the transaction
     *
     * @return effectiveGasPrice
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_EFFECTIVE_GAS_PRICE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getEffectiveGasPrice() {
        return effectiveGasPrice;
    }

    @JsonProperty(JSON_PROPERTY_EFFECTIVE_GAS_PRICE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEffectiveGasPrice(@jakarta.annotation.Nonnull String effectiveGasPrice) {
        this.effectiveGasPrice = effectiveGasPrice;
    }

    public OnchainTransaction fromAddress(@jakarta.annotation.Nonnull String fromAddress) {
        this.fromAddress = fromAddress;
        return this;
    }

    /**
     * Address that initiated the transaction
     *
     * @return fromAddress
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_FROM_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getFromAddress() {
        return fromAddress;
    }

    @JsonProperty(JSON_PROPERTY_FROM_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFromAddress(@jakarta.annotation.Nonnull String fromAddress) {
        this.fromAddress = fromAddress;
    }

    public OnchainTransaction gasUsed(@jakarta.annotation.Nonnull String gasUsed) {
        this.gasUsed = gasUsed;
        return this;
    }

    /**
     * Amount of gas used by this transaction
     *
     * @return gasUsed
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_GAS_USED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getGasUsed() {
        return gasUsed;
    }

    @JsonProperty(JSON_PROPERTY_GAS_USED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setGasUsed(@jakarta.annotation.Nonnull String gasUsed) {
        this.gasUsed = gasUsed;
    }

    public OnchainTransaction status(@jakarta.annotation.Nonnull String status) {
        this.status = status;
        return this;
    }

    /**
     * Transaction status
     *
     * @return status
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStatus(@jakarta.annotation.Nonnull String status) {
        this.status = status;
    }

    public OnchainTransaction toAddress(@jakarta.annotation.Nullable String toAddress) {
        this.toAddress = toAddress;
        return this;
    }

    /**
     * Address that received the transaction
     *
     * @return toAddress
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TO_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getToAddress() {
        return toAddress;
    }

    @JsonProperty(JSON_PROPERTY_TO_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setToAddress(@jakarta.annotation.Nullable String toAddress) {
        this.toAddress = toAddress;
    }

    public OnchainTransaction transactionHash(@jakarta.annotation.Nonnull String transactionHash) {
        this.transactionHash = transactionHash;
        return this;
    }

    /**
     * Hash of the transaction
     *
     * @return transactionHash
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getTransactionHash() {
        return transactionHash;
    }

    @JsonProperty(JSON_PROPERTY_TRANSACTION_HASH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTransactionHash(@jakarta.annotation.Nonnull String transactionHash) {
        this.transactionHash = transactionHash;
    }

    public OnchainTransaction transactionIndex(
            @jakarta.annotation.Nonnull String transactionIndex) {
        this.transactionIndex = transactionIndex;
        return this;
    }

    /**
     * Index of the transaction in the block
     *
     * @return transactionIndex
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TRANSACTION_INDEX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getTransactionIndex() {
        return transactionIndex;
    }

    @JsonProperty(JSON_PROPERTY_TRANSACTION_INDEX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTransactionIndex(@jakarta.annotation.Nonnull String transactionIndex) {
        this.transactionIndex = transactionIndex;
    }

    public OnchainTransaction type(@jakarta.annotation.Nonnull String type) {
        this.type = type;
        return this;
    }

    /**
     * Transaction type
     *
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@jakarta.annotation.Nonnull String type) {
        this.type = type;
    }

    /** Return true if this OnchainTransaction object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OnchainTransaction onchainTransaction = (OnchainTransaction) o;
        return Objects.equals(this.id, onchainTransaction.id)
                && Objects.equals(this.baseAssetId, onchainTransaction.baseAssetId)
                && Objects.equals(this.blockHash, onchainTransaction.blockHash)
                && Objects.equals(this.blockNumber, onchainTransaction.blockNumber)
                && Objects.equals(this.blockTimestamp, onchainTransaction.blockTimestamp)
                && Objects.equals(this.chainId, onchainTransaction.chainId)
                && Objects.equals(this.contractAddress, onchainTransaction.contractAddress)
                && Objects.equals(this.cumulativeGasUsed, onchainTransaction.cumulativeGasUsed)
                && Objects.equals(this.decodedLogs, onchainTransaction.decodedLogs)
                && Objects.equals(this.effectiveGasPrice, onchainTransaction.effectiveGasPrice)
                && Objects.equals(this.fromAddress, onchainTransaction.fromAddress)
                && Objects.equals(this.gasUsed, onchainTransaction.gasUsed)
                && Objects.equals(this.status, onchainTransaction.status)
                && Objects.equals(this.toAddress, onchainTransaction.toAddress)
                && Objects.equals(this.transactionHash, onchainTransaction.transactionHash)
                && Objects.equals(this.transactionIndex, onchainTransaction.transactionIndex)
                && Objects.equals(this.type, onchainTransaction.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                id,
                baseAssetId,
                blockHash,
                blockNumber,
                blockTimestamp,
                chainId,
                contractAddress,
                cumulativeGasUsed,
                decodedLogs,
                effectiveGasPrice,
                fromAddress,
                gasUsed,
                status,
                toAddress,
                transactionHash,
                transactionIndex,
                type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OnchainTransaction {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    baseAssetId: ").append(toIndentedString(baseAssetId)).append("\n");
        sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
        sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
        sb.append("    blockTimestamp: ").append(toIndentedString(blockTimestamp)).append("\n");
        sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
        sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
        sb.append("    cumulativeGasUsed: ")
                .append(toIndentedString(cumulativeGasUsed))
                .append("\n");
        sb.append("    decodedLogs: ").append(toIndentedString(decodedLogs)).append("\n");
        sb.append("    effectiveGasPrice: ")
                .append(toIndentedString(effectiveGasPrice))
                .append("\n");
        sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
        sb.append("    gasUsed: ").append(toIndentedString(gasUsed)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
        sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
        sb.append("    transactionIndex: ").append(toIndentedString(transactionIndex)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(
                    String.format(
                            "%sid%s=%s",
                            prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
        }

        // add `baseAssetId` to the URL query string
        if (getBaseAssetId() != null) {
            joiner.add(
                    String.format(
                            "%sbaseAssetId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBaseAssetId()))));
        }

        // add `blockHash` to the URL query string
        if (getBlockHash() != null) {
            joiner.add(
                    String.format(
                            "%sblockHash%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBlockHash()))));
        }

        // add `blockNumber` to the URL query string
        if (getBlockNumber() != null) {
            joiner.add(
                    String.format(
                            "%sblockNumber%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBlockNumber()))));
        }

        // add `blockTimestamp` to the URL query string
        if (getBlockTimestamp() != null) {
            joiner.add(
                    String.format(
                            "%sblockTimestamp%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBlockTimestamp()))));
        }

        // add `chainId` to the URL query string
        if (getChainId() != null) {
            joiner.add(
                    String.format(
                            "%schainId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getChainId()))));
        }

        // add `contractAddress` to the URL query string
        if (getContractAddress() != null) {
            joiner.add(
                    String.format(
                            "%scontractAddress%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getContractAddress()))));
        }

        // add `cumulativeGasUsed` to the URL query string
        if (getCumulativeGasUsed() != null) {
            joiner.add(
                    String.format(
                            "%scumulativeGasUsed%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getCumulativeGasUsed()))));
        }

        // add `decodedLogs` to the URL query string
        if (getDecodedLogs() != null) {
            joiner.add(getDecodedLogs().toUrlQueryString(prefix + "decodedLogs" + suffix));
        }

        // add `effectiveGasPrice` to the URL query string
        if (getEffectiveGasPrice() != null) {
            joiner.add(
                    String.format(
                            "%seffectiveGasPrice%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getEffectiveGasPrice()))));
        }

        // add `fromAddress` to the URL query string
        if (getFromAddress() != null) {
            joiner.add(
                    String.format(
                            "%sfromAddress%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getFromAddress()))));
        }

        // add `gasUsed` to the URL query string
        if (getGasUsed() != null) {
            joiner.add(
                    String.format(
                            "%sgasUsed%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getGasUsed()))));
        }

        // add `status` to the URL query string
        if (getStatus() != null) {
            joiner.add(
                    String.format(
                            "%sstatus%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
        }

        // add `toAddress` to the URL query string
        if (getToAddress() != null) {
            joiner.add(
                    String.format(
                            "%stoAddress%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getToAddress()))));
        }

        // add `transactionHash` to the URL query string
        if (getTransactionHash() != null) {
            joiner.add(
                    String.format(
                            "%stransactionHash%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getTransactionHash()))));
        }

        // add `transactionIndex` to the URL query string
        if (getTransactionIndex() != null) {
            joiner.add(
                    String.format(
                            "%stransactionIndex%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getTransactionIndex()))));
        }

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(
                    String.format(
                            "%stype%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getType()))));
        }

        return joiner.toString();
    }
}
