/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fireblocks.sdk.ApiClient;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/** Opportunity */
@JsonPropertyOrder({
    Opportunity.JSON_PROPERTY_ID,
    Opportunity.JSON_PROPERTY_PROVIDER_ID,
    Opportunity.JSON_PROPERTY_TYPE,
    Opportunity.JSON_PROPERTY_CHAIN_ID,
    Opportunity.JSON_PROPERTY_ADDRESS,
    Opportunity.JSON_PROPERTY_NAME,
    Opportunity.JSON_PROPERTY_SYMBOL,
    Opportunity.JSON_PROPERTY_PRINCIPAL_ASSET,
    Opportunity.JSON_PROPERTY_POSITION_ASSET,
    Opportunity.JSON_PROPERTY_TOTAL_ASSETS,
    Opportunity.JSON_PROPERTY_LIQUIDITY,
    Opportunity.JSON_PROPERTY_APY,
    Opportunity.JSON_PROPERTY_PERFORMANCE_FEE,
    Opportunity.JSON_PROPERTY_MANAGEMENT_FEE,
    Opportunity.JSON_PROPERTY_EXPOSURE
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class Opportunity {
    public static final String JSON_PROPERTY_ID = "id";
    @jakarta.annotation.Nullable private String id;

    /** Lending protocol (&#x60;MORPHO&#x60; or &#x60;AAVE&#x60;). */
    public enum ProviderIdEnum {
        MORPHO(String.valueOf("MORPHO")),

        AAVE(String.valueOf("AAVE"));

        private String value;

        ProviderIdEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static ProviderIdEnum fromValue(String value) {
            for (ProviderIdEnum b : ProviderIdEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_PROVIDER_ID = "providerId";
    @jakarta.annotation.Nullable private ProviderIdEnum providerId;

    /** Opportunity kind — vault or market. */
    public enum TypeEnum {
        VAULT(String.valueOf("VAULT")),

        MARKET(String.valueOf("MARKET"));

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_TYPE = "type";
    @jakarta.annotation.Nullable private TypeEnum type;

    public static final String JSON_PROPERTY_CHAIN_ID = "chainId";
    @jakarta.annotation.Nullable private String chainId;

    public static final String JSON_PROPERTY_ADDRESS = "address";
    @jakarta.annotation.Nullable private String address;

    public static final String JSON_PROPERTY_NAME = "name";
    @jakarta.annotation.Nullable private String name;

    public static final String JSON_PROPERTY_SYMBOL = "symbol";
    @jakarta.annotation.Nullable private String symbol;

    public static final String JSON_PROPERTY_PRINCIPAL_ASSET = "principalAsset";
    @jakarta.annotation.Nullable private EarnAsset principalAsset;

    public static final String JSON_PROPERTY_POSITION_ASSET = "positionAsset";
    @jakarta.annotation.Nullable private EarnAsset positionAsset;

    public static final String JSON_PROPERTY_TOTAL_ASSETS = "totalAssets";
    @jakarta.annotation.Nullable private String totalAssets;

    public static final String JSON_PROPERTY_LIQUIDITY = "liquidity";
    @jakarta.annotation.Nullable private String liquidity;

    public static final String JSON_PROPERTY_APY = "apy";
    @jakarta.annotation.Nullable private Apy apy;

    public static final String JSON_PROPERTY_PERFORMANCE_FEE = "performanceFee";
    @jakarta.annotation.Nullable private String performanceFee;

    public static final String JSON_PROPERTY_MANAGEMENT_FEE = "managementFee";
    @jakarta.annotation.Nullable private String managementFee;

    public static final String JSON_PROPERTY_EXPOSURE = "exposure";
    @jakarta.annotation.Nullable private List<Exposure> exposure;

    public Opportunity() {}

    public Opportunity id(@jakarta.annotation.Nullable String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique opportunity identifier.
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public Opportunity providerId(@jakarta.annotation.Nullable ProviderIdEnum providerId) {
        this.providerId = providerId;
        return this;
    }

    /**
     * Lending protocol (&#x60;MORPHO&#x60; or &#x60;AAVE&#x60;).
     *
     * @return providerId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROVIDER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ProviderIdEnum getProviderId() {
        return providerId;
    }

    @JsonProperty(JSON_PROPERTY_PROVIDER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProviderId(@jakarta.annotation.Nullable ProviderIdEnum providerId) {
        this.providerId = providerId;
    }

    public Opportunity type(@jakarta.annotation.Nullable TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Opportunity kind — vault or market.
     *
     * @return type
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@jakarta.annotation.Nullable TypeEnum type) {
        this.type = type;
    }

    public Opportunity chainId(@jakarta.annotation.Nullable String chainId) {
        this.chainId = chainId;
        return this;
    }

    /**
     * Chain identifier as a string (e.g. \&quot;1\&quot; for Ethereum mainnet).
     *
     * @return chainId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHAIN_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getChainId() {
        return chainId;
    }

    @JsonProperty(JSON_PROPERTY_CHAIN_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setChainId(@jakarta.annotation.Nullable String chainId) {
        this.chainId = chainId;
    }

    public Opportunity address(@jakarta.annotation.Nullable String address) {
        this.address = address;
        return this;
    }

    /**
     * Primary contract address for the vault or market.
     *
     * @return address
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAddress() {
        return address;
    }

    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAddress(@jakarta.annotation.Nullable String address) {
        this.address = address;
    }

    public Opportunity name(@jakarta.annotation.Nullable String name) {
        this.name = name;
        return this;
    }

    /**
     * Display name of the opportunity.
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    public Opportunity symbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol or share token ticker for the position asset.
     *
     * @return symbol
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SYMBOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSymbol() {
        return symbol;
    }

    @JsonProperty(JSON_PROPERTY_SYMBOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSymbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
    }

    public Opportunity principalAsset(@jakarta.annotation.Nullable EarnAsset principalAsset) {
        this.principalAsset = principalAsset;
        return this;
    }

    /**
     * Underlying token the user deposits (principal).
     *
     * @return principalAsset
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRINCIPAL_ASSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public EarnAsset getPrincipalAsset() {
        return principalAsset;
    }

    @JsonProperty(JSON_PROPERTY_PRINCIPAL_ASSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrincipalAsset(@jakarta.annotation.Nullable EarnAsset principalAsset) {
        this.principalAsset = principalAsset;
    }

    public Opportunity positionAsset(@jakarta.annotation.Nullable EarnAsset positionAsset) {
        this.positionAsset = positionAsset;
        return this;
    }

    /**
     * Token representing the user’s position in the protocol (e.g. vault share).
     *
     * @return positionAsset
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POSITION_ASSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public EarnAsset getPositionAsset() {
        return positionAsset;
    }

    @JsonProperty(JSON_PROPERTY_POSITION_ASSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPositionAsset(@jakarta.annotation.Nullable EarnAsset positionAsset) {
        this.positionAsset = positionAsset;
    }

    public Opportunity totalAssets(@jakarta.annotation.Nullable String totalAssets) {
        this.totalAssets = totalAssets;
        return this;
    }

    /**
     * Human-readable total value locked / assets in the opportunity.
     *
     * @return totalAssets
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TOTAL_ASSETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTotalAssets() {
        return totalAssets;
    }

    @JsonProperty(JSON_PROPERTY_TOTAL_ASSETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalAssets(@jakarta.annotation.Nullable String totalAssets) {
        this.totalAssets = totalAssets;
    }

    public Opportunity liquidity(@jakarta.annotation.Nullable String liquidity) {
        this.liquidity = liquidity;
        return this;
    }

    /**
     * Human-readable available liquidity.
     *
     * @return liquidity
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LIQUIDITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getLiquidity() {
        return liquidity;
    }

    @JsonProperty(JSON_PROPERTY_LIQUIDITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLiquidity(@jakarta.annotation.Nullable String liquidity) {
        this.liquidity = liquidity;
    }

    public Opportunity apy(@jakarta.annotation.Nullable Apy apy) {
        this.apy = apy;
        return this;
    }

    /**
     * APY breakdown; values are percentages (e.g. 4.25 means 4.25%).
     *
     * @return apy
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_APY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Apy getApy() {
        return apy;
    }

    @JsonProperty(JSON_PROPERTY_APY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setApy(@jakarta.annotation.Nullable Apy apy) {
        this.apy = apy;
    }

    public Opportunity performanceFee(@jakarta.annotation.Nullable String performanceFee) {
        this.performanceFee = performanceFee;
        return this;
    }

    /**
     * Performance fee as a human-readable decimal string.
     *
     * @return performanceFee
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PERFORMANCE_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getPerformanceFee() {
        return performanceFee;
    }

    @JsonProperty(JSON_PROPERTY_PERFORMANCE_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPerformanceFee(@jakarta.annotation.Nullable String performanceFee) {
        this.performanceFee = performanceFee;
    }

    public Opportunity managementFee(@jakarta.annotation.Nullable String managementFee) {
        this.managementFee = managementFee;
        return this;
    }

    /**
     * Management fee as a human-readable decimal string.
     *
     * @return managementFee
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MANAGEMENT_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getManagementFee() {
        return managementFee;
    }

    @JsonProperty(JSON_PROPERTY_MANAGEMENT_FEE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setManagementFee(@jakarta.annotation.Nullable String managementFee) {
        this.managementFee = managementFee;
    }

    public Opportunity exposure(@jakarta.annotation.Nullable List<Exposure> exposure) {
        this.exposure = exposure;
        return this;
    }

    public Opportunity addExposureItem(Exposure exposureItem) {
        if (this.exposure == null) {
            this.exposure = new ArrayList<>();
        }
        this.exposure.add(exposureItem);
        return this;
    }

    /**
     * Optional per-asset exposure breakdown.
     *
     * @return exposure
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EXPOSURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<Exposure> getExposure() {
        return exposure;
    }

    @JsonProperty(JSON_PROPERTY_EXPOSURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExposure(@jakarta.annotation.Nullable List<Exposure> exposure) {
        this.exposure = exposure;
    }

    /** Return true if this Opportunity object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Opportunity opportunity = (Opportunity) o;
        return Objects.equals(this.id, opportunity.id)
                && Objects.equals(this.providerId, opportunity.providerId)
                && Objects.equals(this.type, opportunity.type)
                && Objects.equals(this.chainId, opportunity.chainId)
                && Objects.equals(this.address, opportunity.address)
                && Objects.equals(this.name, opportunity.name)
                && Objects.equals(this.symbol, opportunity.symbol)
                && Objects.equals(this.principalAsset, opportunity.principalAsset)
                && Objects.equals(this.positionAsset, opportunity.positionAsset)
                && Objects.equals(this.totalAssets, opportunity.totalAssets)
                && Objects.equals(this.liquidity, opportunity.liquidity)
                && Objects.equals(this.apy, opportunity.apy)
                && Objects.equals(this.performanceFee, opportunity.performanceFee)
                && Objects.equals(this.managementFee, opportunity.managementFee)
                && Objects.equals(this.exposure, opportunity.exposure);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                id,
                providerId,
                type,
                chainId,
                address,
                name,
                symbol,
                principalAsset,
                positionAsset,
                totalAssets,
                liquidity,
                apy,
                performanceFee,
                managementFee,
                exposure);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Opportunity {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
        sb.append("    address: ").append(toIndentedString(address)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("    principalAsset: ").append(toIndentedString(principalAsset)).append("\n");
        sb.append("    positionAsset: ").append(toIndentedString(positionAsset)).append("\n");
        sb.append("    totalAssets: ").append(toIndentedString(totalAssets)).append("\n");
        sb.append("    liquidity: ").append(toIndentedString(liquidity)).append("\n");
        sb.append("    apy: ").append(toIndentedString(apy)).append("\n");
        sb.append("    performanceFee: ").append(toIndentedString(performanceFee)).append("\n");
        sb.append("    managementFee: ").append(toIndentedString(managementFee)).append("\n");
        sb.append("    exposure: ").append(toIndentedString(exposure)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(
                    String.format(
                            "%sid%s=%s",
                            prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
        }

        // add `providerId` to the URL query string
        if (getProviderId() != null) {
            joiner.add(
                    String.format(
                            "%sproviderId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getProviderId()))));
        }

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(
                    String.format(
                            "%stype%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getType()))));
        }

        // add `chainId` to the URL query string
        if (getChainId() != null) {
            joiner.add(
                    String.format(
                            "%schainId%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getChainId()))));
        }

        // add `address` to the URL query string
        if (getAddress() != null) {
            joiner.add(
                    String.format(
                            "%saddress%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getAddress()))));
        }

        // add `name` to the URL query string
        if (getName() != null) {
            joiner.add(
                    String.format(
                            "%sname%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getName()))));
        }

        // add `symbol` to the URL query string
        if (getSymbol() != null) {
            joiner.add(
                    String.format(
                            "%ssymbol%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getSymbol()))));
        }

        // add `principalAsset` to the URL query string
        if (getPrincipalAsset() != null) {
            joiner.add(getPrincipalAsset().toUrlQueryString(prefix + "principalAsset" + suffix));
        }

        // add `positionAsset` to the URL query string
        if (getPositionAsset() != null) {
            joiner.add(getPositionAsset().toUrlQueryString(prefix + "positionAsset" + suffix));
        }

        // add `totalAssets` to the URL query string
        if (getTotalAssets() != null) {
            joiner.add(
                    String.format(
                            "%stotalAssets%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getTotalAssets()))));
        }

        // add `liquidity` to the URL query string
        if (getLiquidity() != null) {
            joiner.add(
                    String.format(
                            "%sliquidity%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getLiquidity()))));
        }

        // add `apy` to the URL query string
        if (getApy() != null) {
            joiner.add(getApy().toUrlQueryString(prefix + "apy" + suffix));
        }

        // add `performanceFee` to the URL query string
        if (getPerformanceFee() != null) {
            joiner.add(
                    String.format(
                            "%sperformanceFee%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getPerformanceFee()))));
        }

        // add `managementFee` to the URL query string
        if (getManagementFee() != null) {
            joiner.add(
                    String.format(
                            "%smanagementFee%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getManagementFee()))));
        }

        // add `exposure` to the URL query string
        if (getExposure() != null) {
            for (int i = 0; i < getExposure().size(); i++) {
                if (getExposure().get(i) != null) {
                    joiner.add(
                            getExposure()
                                    .get(i)
                                    .toUrlQueryString(
                                            String.format(
                                                    "%sexposure%s%s",
                                                    prefix,
                                                    suffix,
                                                    "".equals(suffix)
                                                            ? ""
                                                            : String.format(
                                                                    "%s%d%s",
                                                                    containerPrefix,
                                                                    i,
                                                                    containerSuffix))));
                }
            }
        }

        return joiner.toString();
    }
}
