/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fireblocks.sdk.ApiClient;
import java.util.Objects;
import java.util.StringJoiner;

/** PayidAddress */
@JsonPropertyOrder({
    PayidAddress.JSON_PROPERTY_ACCOUNT_HOLDER,
    PayidAddress.JSON_PROPERTY_VALUE,
    PayidAddress.JSON_PROPERTY_TYPE,
    PayidAddress.JSON_PROPERTY_BSB,
    PayidAddress.JSON_PROPERTY_ACCOUNT_NUMBER
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class PayidAddress {
    public static final String JSON_PROPERTY_ACCOUNT_HOLDER = "accountHolder";
    @jakarta.annotation.Nonnull private AccountHolderDetails accountHolder;

    public static final String JSON_PROPERTY_VALUE = "value";
    @jakarta.annotation.Nonnull private String value;

    /** The type of PayID being used */
    public enum TypeEnum {
        EMAIL(String.valueOf("EMAIL"));

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_TYPE = "type";
    @jakarta.annotation.Nonnull private TypeEnum type;

    public static final String JSON_PROPERTY_BSB = "bsb";
    @jakarta.annotation.Nullable private String bsb;

    public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "accountNumber";
    @jakarta.annotation.Nonnull private String accountNumber;

    public PayidAddress() {}

    @JsonCreator
    public PayidAddress(
            @JsonProperty(value = JSON_PROPERTY_ACCOUNT_HOLDER, required = true)
                    AccountHolderDetails accountHolder,
            @JsonProperty(value = JSON_PROPERTY_VALUE, required = true) String value,
            @JsonProperty(value = JSON_PROPERTY_TYPE, required = true) TypeEnum type,
            @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NUMBER, required = true)
                    String accountNumber) {
        this.accountHolder = accountHolder;
        this.value = value;
        this.type = type;
        this.accountNumber = accountNumber;
    }

    public PayidAddress accountHolder(
            @jakarta.annotation.Nonnull AccountHolderDetails accountHolder) {
        this.accountHolder = accountHolder;
        return this;
    }

    /**
     * Get accountHolder
     *
     * @return accountHolder
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public AccountHolderDetails getAccountHolder() {
        return accountHolder;
    }

    @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAccountHolder(@jakarta.annotation.Nonnull AccountHolderDetails accountHolder) {
        this.accountHolder = accountHolder;
    }

    public PayidAddress value(@jakarta.annotation.Nonnull String value) {
        this.value = value;
        return this;
    }

    /**
     * The PayID identifier (email, phone, ABN, or organization ID)
     *
     * @return value
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getValue() {
        return value;
    }

    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setValue(@jakarta.annotation.Nonnull String value) {
        this.value = value;
    }

    public PayidAddress type(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * The type of PayID being used
     *
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
    }

    public PayidAddress bsb(@jakarta.annotation.Nullable String bsb) {
        this.bsb = bsb;
        return this;
    }

    /**
     * Bank State Branch (BSB) number (6 digits, format XXX-XXX)
     *
     * @return bsb
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BSB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBsb() {
        return bsb;
    }

    @JsonProperty(JSON_PROPERTY_BSB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBsb(@jakarta.annotation.Nullable String bsb) {
        this.bsb = bsb;
    }

    public PayidAddress accountNumber(@jakarta.annotation.Nonnull String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * Australian bank account number
     *
     * @return accountNumber
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getAccountNumber() {
        return accountNumber;
    }

    @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAccountNumber(@jakarta.annotation.Nonnull String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /** Return true if this PayidAddress object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayidAddress payidAddress = (PayidAddress) o;
        return Objects.equals(this.accountHolder, payidAddress.accountHolder)
                && Objects.equals(this.value, payidAddress.value)
                && Objects.equals(this.type, payidAddress.type)
                && Objects.equals(this.bsb, payidAddress.bsb)
                && Objects.equals(this.accountNumber, payidAddress.accountNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accountHolder, value, type, bsb, accountNumber);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PayidAddress {\n");
        sb.append("    accountHolder: ").append(toIndentedString(accountHolder)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    bsb: ").append(toIndentedString(bsb)).append("\n");
        sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `accountHolder` to the URL query string
        if (getAccountHolder() != null) {
            joiner.add(getAccountHolder().toUrlQueryString(prefix + "accountHolder" + suffix));
        }

        // add `value` to the URL query string
        if (getValue() != null) {
            joiner.add(
                    String.format(
                            "%svalue%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
        }

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(
                    String.format(
                            "%stype%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getType()))));
        }

        // add `bsb` to the URL query string
        if (getBsb() != null) {
            joiner.add(
                    String.format(
                            "%sbsb%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBsb()))));
        }

        // add `accountNumber` to the URL query string
        if (getAccountNumber() != null) {
            joiner.add(
                    String.format(
                            "%saccountNumber%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getAccountNumber()))));
        }

        return joiner.toString();
    }
}
