/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fireblocks.sdk.ApiClient;
import java.util.Objects;
import java.util.StringJoiner;

/** PixAddress */
@JsonPropertyOrder({
    PixAddress.JSON_PROPERTY_ACCOUNT_HOLDER,
    PixAddress.JSON_PROPERTY_PIX_KEY,
    PixAddress.JSON_PROPERTY_KEY_TYPE,
    PixAddress.JSON_PROPERTY_BANK_NAME,
    PixAddress.JSON_PROPERTY_BANK_CODE,
    PixAddress.JSON_PROPERTY_QR_CODE,
    PixAddress.JSON_PROPERTY_EXPIRATION_DATE
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class PixAddress {
    public static final String JSON_PROPERTY_ACCOUNT_HOLDER = "accountHolder";
    @jakarta.annotation.Nonnull private AccountHolderDetails accountHolder;

    public static final String JSON_PROPERTY_PIX_KEY = "pixKey";
    @jakarta.annotation.Nonnull private String pixKey;

    /** Gets or Sets keyType */
    public enum KeyTypeEnum {
        CPF(String.valueOf("CPF")),

        CNPJ(String.valueOf("CNPJ")),

        EMAIL(String.valueOf("EMAIL")),

        PHONE(String.valueOf("PHONE")),

        RANDOM(String.valueOf("RANDOM"));

        private String value;

        KeyTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static KeyTypeEnum fromValue(String value) {
            for (KeyTypeEnum b : KeyTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_KEY_TYPE = "keyType";
    @jakarta.annotation.Nonnull private KeyTypeEnum keyType;

    public static final String JSON_PROPERTY_BANK_NAME = "bankName";
    @jakarta.annotation.Nullable private String bankName;

    public static final String JSON_PROPERTY_BANK_CODE = "bankCode";
    @jakarta.annotation.Nullable private String bankCode;

    public static final String JSON_PROPERTY_QR_CODE = "qrCode";
    @jakarta.annotation.Nullable private String qrCode;

    public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
    @jakarta.annotation.Nullable private String expirationDate;

    public PixAddress() {}

    @JsonCreator
    public PixAddress(
            @JsonProperty(value = JSON_PROPERTY_ACCOUNT_HOLDER, required = true)
                    AccountHolderDetails accountHolder,
            @JsonProperty(value = JSON_PROPERTY_PIX_KEY, required = true) String pixKey,
            @JsonProperty(value = JSON_PROPERTY_KEY_TYPE, required = true) KeyTypeEnum keyType) {
        this.accountHolder = accountHolder;
        this.pixKey = pixKey;
        this.keyType = keyType;
    }

    public PixAddress accountHolder(
            @jakarta.annotation.Nonnull AccountHolderDetails accountHolder) {
        this.accountHolder = accountHolder;
        return this;
    }

    /**
     * Get accountHolder
     *
     * @return accountHolder
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public AccountHolderDetails getAccountHolder() {
        return accountHolder;
    }

    @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAccountHolder(@jakarta.annotation.Nonnull AccountHolderDetails accountHolder) {
        this.accountHolder = accountHolder;
    }

    public PixAddress pixKey(@jakarta.annotation.Nonnull String pixKey) {
        this.pixKey = pixKey;
        return this;
    }

    /**
     * Get pixKey
     *
     * @return pixKey
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_PIX_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getPixKey() {
        return pixKey;
    }

    @JsonProperty(JSON_PROPERTY_PIX_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPixKey(@jakarta.annotation.Nonnull String pixKey) {
        this.pixKey = pixKey;
    }

    public PixAddress keyType(@jakarta.annotation.Nonnull KeyTypeEnum keyType) {
        this.keyType = keyType;
        return this;
    }

    /**
     * Get keyType
     *
     * @return keyType
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_KEY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public KeyTypeEnum getKeyType() {
        return keyType;
    }

    @JsonProperty(JSON_PROPERTY_KEY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setKeyType(@jakarta.annotation.Nonnull KeyTypeEnum keyType) {
        this.keyType = keyType;
    }

    public PixAddress bankName(@jakarta.annotation.Nullable String bankName) {
        this.bankName = bankName;
        return this;
    }

    /**
     * Get bankName
     *
     * @return bankName
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BANK_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBankName() {
        return bankName;
    }

    @JsonProperty(JSON_PROPERTY_BANK_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBankName(@jakarta.annotation.Nullable String bankName) {
        this.bankName = bankName;
    }

    public PixAddress bankCode(@jakarta.annotation.Nullable String bankCode) {
        this.bankCode = bankCode;
        return this;
    }

    /**
     * Get bankCode
     *
     * @return bankCode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BANK_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBankCode() {
        return bankCode;
    }

    @JsonProperty(JSON_PROPERTY_BANK_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBankCode(@jakarta.annotation.Nullable String bankCode) {
        this.bankCode = bankCode;
    }

    public PixAddress qrCode(@jakarta.annotation.Nullable String qrCode) {
        this.qrCode = qrCode;
        return this;
    }

    /**
     * The QR code to be used for the transfer
     *
     * @return qrCode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_QR_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getQrCode() {
        return qrCode;
    }

    @JsonProperty(JSON_PROPERTY_QR_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setQrCode(@jakarta.annotation.Nullable String qrCode) {
        this.qrCode = qrCode;
    }

    public PixAddress expirationDate(@jakarta.annotation.Nullable String expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * The expiration date of the QR code
     *
     * @return expirationDate
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getExpirationDate() {
        return expirationDate;
    }

    @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExpirationDate(@jakarta.annotation.Nullable String expirationDate) {
        this.expirationDate = expirationDate;
    }

    /** Return true if this PixAddress object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PixAddress pixAddress = (PixAddress) o;
        return Objects.equals(this.accountHolder, pixAddress.accountHolder)
                && Objects.equals(this.pixKey, pixAddress.pixKey)
                && Objects.equals(this.keyType, pixAddress.keyType)
                && Objects.equals(this.bankName, pixAddress.bankName)
                && Objects.equals(this.bankCode, pixAddress.bankCode)
                && Objects.equals(this.qrCode, pixAddress.qrCode)
                && Objects.equals(this.expirationDate, pixAddress.expirationDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                accountHolder, pixKey, keyType, bankName, bankCode, qrCode, expirationDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PixAddress {\n");
        sb.append("    accountHolder: ").append(toIndentedString(accountHolder)).append("\n");
        sb.append("    pixKey: ").append(toIndentedString(pixKey)).append("\n");
        sb.append("    keyType: ").append(toIndentedString(keyType)).append("\n");
        sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
        sb.append("    bankCode: ").append(toIndentedString(bankCode)).append("\n");
        sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
        sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `accountHolder` to the URL query string
        if (getAccountHolder() != null) {
            joiner.add(getAccountHolder().toUrlQueryString(prefix + "accountHolder" + suffix));
        }

        // add `pixKey` to the URL query string
        if (getPixKey() != null) {
            joiner.add(
                    String.format(
                            "%spixKey%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getPixKey()))));
        }

        // add `keyType` to the URL query string
        if (getKeyType() != null) {
            joiner.add(
                    String.format(
                            "%skeyType%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getKeyType()))));
        }

        // add `bankName` to the URL query string
        if (getBankName() != null) {
            joiner.add(
                    String.format(
                            "%sbankName%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBankName()))));
        }

        // add `bankCode` to the URL query string
        if (getBankCode() != null) {
            joiner.add(
                    String.format(
                            "%sbankCode%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getBankCode()))));
        }

        // add `qrCode` to the URL query string
        if (getQrCode() != null) {
            joiner.add(
                    String.format(
                            "%sqrCode%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getQrCode()))));
        }

        // add `expirationDate` to the URL query string
        if (getExpirationDate() != null) {
            joiner.add(
                    String.format(
                            "%sexpirationDate%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getExpirationDate()))));
        }

        return joiner.toString();
    }
}
