/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

/** Provider specific additional data */
@JsonPropertyOrder({ProviderAdditionalData.JSON_PROPERTY_PRICE_IMPACT})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProviderAdditionalData {
    public static final String JSON_PROPERTY_PRICE_IMPACT = "priceImpact";
    private String priceImpact;

    public ProviderAdditionalData() {}

    public ProviderAdditionalData priceImpact(String priceImpact) {
        this.priceImpact = priceImpact;
        return this;
    }

    /**
     * Get priceImpact
     *
     * @return priceImpact
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_PRICE_IMPACT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getPriceImpact() {
        return priceImpact;
    }

    @JsonProperty(JSON_PROPERTY_PRICE_IMPACT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPriceImpact(String priceImpact) {
        this.priceImpact = priceImpact;
    }

    /** Return true if this ProviderAdditionalData object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProviderAdditionalData providerAdditionalData = (ProviderAdditionalData) o;
        return Objects.equals(this.priceImpact, providerAdditionalData.priceImpact);
    }

    @Override
    public int hashCode() {
        return Objects.hash(priceImpact);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProviderAdditionalData {\n");
        sb.append("    priceImpact: ").append(toIndentedString(priceImpact)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `priceImpact` to the URL query string
        if (getPriceImpact() != null) {
            joiner.add(
                    String.format(
                            "%spriceImpact%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(
                                            String.valueOf(getPriceImpact()),
                                            StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
