/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.fireblocks.sdk.JSON;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.StringJoiner;
import java.util.logging.Level;
import java.util.logging.Logger;

@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
@JsonDeserialize(using = SettlementSourceAccount.SettlementSourceAccountDeserializer.class)
@JsonSerialize(using = SettlementSourceAccount.SettlementSourceAccountSerializer.class)
public class SettlementSourceAccount extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SettlementSourceAccount.class.getName());

    public static class SettlementSourceAccountSerializer
            extends StdSerializer<SettlementSourceAccount> {
        public SettlementSourceAccountSerializer(Class<SettlementSourceAccount> t) {
            super(t);
        }

        public SettlementSourceAccountSerializer() {
            this(null);
        }

        @Override
        public void serialize(
                SettlementSourceAccount value, JsonGenerator jgen, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SettlementSourceAccountDeserializer
            extends StdDeserializer<SettlementSourceAccount> {
        public SettlementSourceAccountDeserializer() {
            this(SettlementSourceAccount.class);
        }

        public SettlementSourceAccountDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SettlementSourceAccount deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize ExternalAccount
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (ExternalAccount.class.equals(Integer.class)
                        || ExternalAccount.class.equals(Long.class)
                        || ExternalAccount.class.equals(Float.class)
                        || ExternalAccount.class.equals(Double.class)
                        || ExternalAccount.class.equals(Boolean.class)
                        || ExternalAccount.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |=
                                ((ExternalAccount.class.equals(Integer.class)
                                                || ExternalAccount.class.equals(Long.class))
                                        && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |=
                                ((ExternalAccount.class.equals(Float.class)
                                                || ExternalAccount.class.equals(Double.class))
                                        && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |=
                                (ExternalAccount.class.equals(Boolean.class)
                                        && (token == JsonToken.VALUE_FALSE
                                                || token == JsonToken.VALUE_TRUE));
                        attemptParsing |=
                                (ExternalAccount.class.equals(String.class)
                                        && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(ExternalAccount.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'ExternalAccount'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'ExternalAccount'", e);
            }

            // deserialize PlatformAccount
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PlatformAccount.class.equals(Integer.class)
                        || PlatformAccount.class.equals(Long.class)
                        || PlatformAccount.class.equals(Float.class)
                        || PlatformAccount.class.equals(Double.class)
                        || PlatformAccount.class.equals(Boolean.class)
                        || PlatformAccount.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |=
                                ((PlatformAccount.class.equals(Integer.class)
                                                || PlatformAccount.class.equals(Long.class))
                                        && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |=
                                ((PlatformAccount.class.equals(Float.class)
                                                || PlatformAccount.class.equals(Double.class))
                                        && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |=
                                (PlatformAccount.class.equals(Boolean.class)
                                        && (token == JsonToken.VALUE_FALSE
                                                || token == JsonToken.VALUE_TRUE));
                        attemptParsing |=
                                (PlatformAccount.class.equals(String.class)
                                        && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PlatformAccount.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PlatformAccount'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PlatformAccount'", e);
            }

            if (match == 1) {
                SettlementSourceAccount ret = new SettlementSourceAccount();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(
                    String.format(
                            "Failed deserialization for SettlementSourceAccount: %d classes match"
                                    + " result, expected 1",
                            match));
        }

        /** Handle deserialization of the 'null' value. */
        @Override
        public SettlementSourceAccount getNullValue(DeserializationContext ctxt)
                throws JsonMappingException {
            throw new JsonMappingException(
                    ctxt.getParser(), "SettlementSourceAccount cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SettlementSourceAccount() {
        super("oneOf", Boolean.FALSE);
    }

    public SettlementSourceAccount(ExternalAccount o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SettlementSourceAccount(PlatformAccount o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ExternalAccount", ExternalAccount.class);
        schemas.put("PlatformAccount", PlatformAccount.class);
        JSON.registerDescendants(
                SettlementSourceAccount.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("CONNECTED_ACCOUNT", PlatformAccount.class);
        mappings.put("EXTERNAL", ExternalAccount.class);
        mappings.put("FIAT_ACCOUNT", PlatformAccount.class);
        mappings.put("VAULT_ACCOUNT", PlatformAccount.class);
        mappings.put("ExternalAccount", ExternalAccount.class);
        mappings.put("PlatformAccount", PlatformAccount.class);
        mappings.put("SettlementSourceAccount", SettlementSourceAccount.class);
        JSON.registerDiscriminator(SettlementSourceAccount.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SettlementSourceAccount.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check the instance parameter is valid
     * against the oneOf child schemas: ExternalAccount, PlatformAccount
     *
     * <p>It could be an instance of the 'oneOf' schemas. The oneOf child schemas may themselves be
     * a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(ExternalAccount.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PlatformAccount.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException(
                "Invalid instance type. Must be ExternalAccount, PlatformAccount");
    }

    /**
     * Get the actual instance, which can be the following: ExternalAccount, PlatformAccount
     *
     * @return The actual instance (ExternalAccount, PlatformAccount)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ExternalAccount`. If the actual instance is not
     * `ExternalAccount`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `ExternalAccount`
     * @throws ClassCastException if the instance is not `ExternalAccount`
     */
    public ExternalAccount getExternalAccount() throws ClassCastException {
        return (ExternalAccount) super.getActualInstance();
    }

    /**
     * Get the actual instance of `PlatformAccount`. If the actual instance is not
     * `PlatformAccount`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `PlatformAccount`
     * @throws ClassCastException if the instance is not `PlatformAccount`
     */
    public PlatformAccount getPlatformAccount() throws ClassCastException {
        return (PlatformAccount) super.getActualInstance();
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        if (getActualInstance() instanceof PlatformAccount) {
            if (getActualInstance() != null) {
                joiner.add(
                        ((PlatformAccount) getActualInstance())
                                .toUrlQueryString(prefix + "one_of_0" + suffix));
            }
            return joiner.toString();
        }
        if (getActualInstance() instanceof ExternalAccount) {
            if (getActualInstance() != null) {
                joiner.add(
                        ((ExternalAccount) getActualInstance())
                                .toUrlQueryString(prefix + "one_of_1" + suffix));
            }
            return joiner.toString();
        }
        return null;
    }
}
