/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/** Source of the transaction. */
@JsonPropertyOrder({
    SourceTransferPeerPathResponse.JSON_PROPERTY_TYPE,
    SourceTransferPeerPathResponse.JSON_PROPERTY_SUB_TYPE,
    SourceTransferPeerPathResponse.JSON_PROPERTY_ID,
    SourceTransferPeerPathResponse.JSON_PROPERTY_NAME,
    SourceTransferPeerPathResponse.JSON_PROPERTY_WALLET_ID,
    SourceTransferPeerPathResponse.JSON_PROPERTY_TRADING_ACCOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SourceTransferPeerPathResponse {
    public static final String JSON_PROPERTY_TYPE = "type";
    private TransferPeerPathType type;

    public static final String JSON_PROPERTY_SUB_TYPE = "subType";
    private String subType;

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_WALLET_ID = "walletId";
    private UUID walletId;

    public static final String JSON_PROPERTY_TRADING_ACCOUNT = "tradingAccount";
    private String tradingAccount;

    public SourceTransferPeerPathResponse() {}

    public SourceTransferPeerPathResponse type(TransferPeerPathType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TransferPeerPathType getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(TransferPeerPathType type) {
        this.type = type;
    }

    public SourceTransferPeerPathResponse subType(String subType) {
        this.subType = subType;
        return this;
    }

    /**
     * In case the type is set to &#x60;EXCHANGE_ACCOUNT&#x60; or &#x60;FIAT_ACCOUNT&#x60;, the
     * specific exchange vendor name or fiat vendor name. In case the type is set to
     * &#x60;INTERNAL_WALLET&#x60; or &#x60;EXTERNAL_WALLET&#x60;, the subType is set to
     * &#x60;Internal&#x60; or &#x60;External&#x60;.
     *
     * @return subType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUB_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSubType() {
        return subType;
    }

    @JsonProperty(JSON_PROPERTY_SUB_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubType(String subType) {
        this.subType = subType;
    }

    public SourceTransferPeerPathResponse id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The ID of the peer. You can retrieve the ID of each venue object using the endpoints for
     * [listing vault accounts](https://developers.fireblocks.com/reference/getpagedvaultaccounts),
     * [listing exchange account](https://developers.fireblocks.com/reference/getexchangeaccounts),
     * [listing fiat accounts](https://developers.fireblocks.com/reference/getfiataccounts),
     * [listing internal wallets](https://developers.fireblocks.com/reference/getinternalwallets),
     * [listing external wallets](https://developers.fireblocks.com/reference/getexternalwallets),
     * [listing network
     * connections](https://developers.fireblocks.com/reference/getnetworkconnections). For the
     * other types, this parameter is not needed.
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public SourceTransferPeerPathResponse name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The name of the peer.
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(String name) {
        this.name = name;
    }

    public SourceTransferPeerPathResponse walletId(UUID walletId) {
        this.walletId = walletId;
        return this;
    }

    /**
     * Get walletId
     *
     * @return walletId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WALLET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public UUID getWalletId() {
        return walletId;
    }

    @JsonProperty(JSON_PROPERTY_WALLET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWalletId(UUID walletId) {
        this.walletId = walletId;
    }

    public SourceTransferPeerPathResponse tradingAccount(String tradingAccount) {
        this.tradingAccount = tradingAccount;
        return this;
    }

    /**
     * If this transaction is an exchange internal transfer, this field will be populated with the
     * type of that trading account.
     *
     * @return tradingAccount
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRADING_ACCOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTradingAccount() {
        return tradingAccount;
    }

    @JsonProperty(JSON_PROPERTY_TRADING_ACCOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTradingAccount(String tradingAccount) {
        this.tradingAccount = tradingAccount;
    }

    /** Return true if this SourceTransferPeerPathResponse object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceTransferPeerPathResponse sourceTransferPeerPathResponse =
                (SourceTransferPeerPathResponse) o;
        return Objects.equals(this.type, sourceTransferPeerPathResponse.type)
                && Objects.equals(this.subType, sourceTransferPeerPathResponse.subType)
                && Objects.equals(this.id, sourceTransferPeerPathResponse.id)
                && Objects.equals(this.name, sourceTransferPeerPathResponse.name)
                && Objects.equals(this.walletId, sourceTransferPeerPathResponse.walletId)
                && Objects.equals(
                        this.tradingAccount, sourceTransferPeerPathResponse.tradingAccount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, subType, id, name, walletId, tradingAccount);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SourceTransferPeerPathResponse {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
        sb.append("    tradingAccount: ").append(toIndentedString(tradingAccount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(
                    String.format(
                            "%stype%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getType()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `subType` to the URL query string
        if (getSubType() != null) {
            joiner.add(
                    String.format(
                            "%ssubType%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getSubType()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(
                    String.format(
                            "%sid%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `name` to the URL query string
        if (getName() != null) {
            joiner.add(
                    String.format(
                            "%sname%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `walletId` to the URL query string
        if (getWalletId() != null) {
            joiner.add(
                    String.format(
                            "%swalletId%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(String.valueOf(getWalletId()), StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        // add `tradingAccount` to the URL query string
        if (getTradingAccount() != null) {
            joiner.add(
                    String.format(
                            "%stradingAccount%s=%s",
                            prefix,
                            suffix,
                            URLEncoder.encode(
                                            String.valueOf(getTradingAccount()),
                                            StandardCharsets.UTF_8)
                                    .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
