/*
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fireblocks.sdk.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fireblocks.sdk.ApiClient;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Config row stored at exactly the requested scope. Omitted from the parent object when none
 * exists; the server does not emit JSON &#x60;null&#x60;.
 */
@JsonPropertyOrder({
    UtxoSelectionConfigEntry.JSON_PROPERTY_STRATEGY,
    UtxoSelectionConfigEntry.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.14.0")
public class UtxoSelectionConfigEntry {
    public static final String JSON_PROPERTY_STRATEGY = "strategy";
    @jakarta.annotation.Nonnull private UtxoSelectionStrategyEnum strategy;

    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    @jakarta.annotation.Nonnull private OffsetDateTime updatedAt;

    public UtxoSelectionConfigEntry() {}

    @JsonCreator
    public UtxoSelectionConfigEntry(
            @JsonProperty(value = JSON_PROPERTY_STRATEGY, required = true)
                    UtxoSelectionStrategyEnum strategy,
            @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
                    OffsetDateTime updatedAt) {
        this.strategy = strategy;
        this.updatedAt = updatedAt;
    }

    public UtxoSelectionConfigEntry strategy(
            @jakarta.annotation.Nonnull UtxoSelectionStrategyEnum strategy) {
        this.strategy = strategy;
        return this;
    }

    /**
     * Get strategy
     *
     * @return strategy
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_STRATEGY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UtxoSelectionStrategyEnum getStrategy() {
        return strategy;
    }

    @JsonProperty(JSON_PROPERTY_STRATEGY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStrategy(@jakarta.annotation.Nonnull UtxoSelectionStrategyEnum strategy) {
        this.strategy = strategy;
    }

    public UtxoSelectionConfigEntry updatedAt(
            @jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Time at which this configured row was last updated.
     *
     * @return updatedAt
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUpdatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /** Return true if this UtxoSelectionConfigEntry object is equal to o. */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UtxoSelectionConfigEntry utxoSelectionConfigEntry = (UtxoSelectionConfigEntry) o;
        return Objects.equals(this.strategy, utxoSelectionConfigEntry.strategy)
                && Objects.equals(this.updatedAt, utxoSelectionConfigEntry.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(strategy, updatedAt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UtxoSelectionConfigEntry {\n");
        sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `strategy` to the URL query string
        if (getStrategy() != null) {
            joiner.add(
                    String.format(
                            "%sstrategy%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getStrategy()))));
        }

        // add `updatedAt` to the URL query string
        if (getUpdatedAt() != null) {
            joiner.add(
                    String.format(
                            "%supdatedAt%s=%s",
                            prefix,
                            suffix,
                            ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
        }

        return joiner.toString();
    }
}
