/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fireblocks.sdk;

import com.fireblocks.sdk.*;
import com.fireblocks.sdk.auth.*;
import com.fireblocks.sdk.Configuration;
import com.fireblocks.sdk.model.Error;
import com.fireblocks.sdk.model.FiatAccount;
import com.fireblocks.sdk.model.RedeemFundsToLinkedDDARequest;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FiatAccountsApi
 */
public class FiatAccountsApiTest {

    private FiatAccountsApi api;

    /**
     * Deposit funds from DDA
     *
     * Deposits funds from the linked DDA.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void depositFundsFromLinkedDDATest() throws ApiException {
        Configuration configuration = new Configuration();
        configuration.setApiKey("test");
        configuration.setSecretKey("test");
        this.api = new FiatAccountsApi(configuration);
        //String accountId = null;
        //RedeemFundsToLinkedDDARequest redeemFundsToLinkedDDARequest = null;
        //api.depositFundsFromLinkedDDA(accountId, redeemFundsToLinkedDDARequest);
        // TODO: test validations
    }

    /**
     * Find a specific fiat account
     *
     * Returns a fiat account by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFiatAccountByIdTest() throws ApiException {
        Configuration configuration = new Configuration();
        configuration.setApiKey("test");
        configuration.setSecretKey("test");
        this.api = new FiatAccountsApi(configuration);
        //String accountId = null;
        //FiatAccount response = api.getFiatAccountById(accountId);
        // TODO: test validations
    }

    /**
     * List fiat accounts
     *
     * Returns all fiat accounts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFiatAccountsTest() throws ApiException {
        Configuration configuration = new Configuration();
        configuration.setApiKey("test");
        configuration.setSecretKey("test");
        this.api = new FiatAccountsApi(configuration);
        //List<FiatAccount> response = api.getFiatAccounts();
        // TODO: test validations
    }

    /**
     * Redeem funds to DDA
     *
     * Redeems funds to the linked DDA.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void redeemFundsToLinkedDDATest() throws ApiException {
        Configuration configuration = new Configuration();
        configuration.setApiKey("test");
        configuration.setSecretKey("test");
        this.api = new FiatAccountsApi(configuration);
        //String accountId = null;
        //RedeemFundsToLinkedDDARequest redeemFundsToLinkedDDARequest = null;
        //api.redeemFundsToLinkedDDA(accountId, redeemFundsToLinkedDDARequest);
        // TODO: test validations
    }

}
