/*
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.TravelRuleGetAllVASPsResponse;
import org.openapitools.client.model.TravelRuleUpdateVASPDetails;
import org.openapitools.client.model.TravelRuleVASP;
import org.openapitools.client.model.TravelRuleValidateFullTransactionRequest;
import org.openapitools.client.model.TravelRuleValidateTransactionRequest;
import org.openapitools.client.model.TravelRuleValidateTransactionResponse;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TravelRuleBetaApi
 */
@Ignore
public class TravelRuleBetaApiTest {

    private final TravelRuleBetaApi api = new TravelRuleBetaApi();

    /**
     * Get VASP details
     *
     * Get VASP Details.  Returns information about a VASP that has the specified DID.  **Note:** The reference content in this section documents the Travel Rule beta endpoint. The beta endpoint includes APIs that are currently in preview and aren&#39;t yet generally available.  To enroll in the beta and enable this endpoint, contact your Fireblocks Customer Success Manager or send an email to [CSM@fireblocks.com](mailto:CSM@fireblocks.com).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVASPByDIDTest() throws ApiException {
        String did = null;
        String fields = null;
        TravelRuleVASP response = api.getVASPByDID(did, fields);

        // TODO: test validations
    }
    /**
     * Get All VASPs
     *
     * Get All VASPs.  Returns a list of VASPs. VASPs can be searched and sorted and results are paginated.  **Note:** The reference content in this section documents the Travel Rule beta endpoint. The beta endpoint includes APIs that are currently in preview and aren&#39;t yet generally available.  To enroll in the beta and enable this endpoint, contact your Fireblocks Customer Success Manager or send an email to [CSM@fireblocks.com](mailto:CSM@fireblocks.com).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVASPsTest() throws ApiException {
        String order = null;
        BigDecimal perPage = null;
        BigDecimal page = null;
        String fields = null;
        TravelRuleGetAllVASPsResponse response = api.getVASPs(order, perPage, page, fields);

        // TODO: test validations
    }
    /**
     * Add jsonDidKey to VASP details
     *
     * Update VASP Details.  Updates a VASP with the provided parameters. Use this endpoint to add your public jsonDIDkey generated by Notabene.  **Note:** The reference content in this section documents the Travel Rule beta endpoint. The beta endpoint includes APIs that are currently in preview and aren&#39;t yet generally available.  To enroll in the beta and enable this endpoint, contact your Fireblocks Customer Success Manager or send an email to [CSM@fireblocks.com](mailto:CSM@fireblocks.com).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void travelRuleApiControllerUpdateVaspTest() throws ApiException {
        TravelRuleUpdateVASPDetails travelRuleUpdateVASPDetails = null;
        TravelRuleUpdateVASPDetails response = api.travelRuleApiControllerUpdateVasp(travelRuleUpdateVASPDetails);

        // TODO: test validations
    }
    /**
     * Validate Full Travel Rule Transaction
     *
     * Validate Full Travel Rule transactions.  Checks for all required information on the originator and beneficiary VASPs.  **Note:** The reference content in this section documents the Travel Rule beta endpoint. The beta endpoint includes APIs that are currently in preview and aren&#39;t yet generally available.  To enroll in the beta and enable this endpoint, contact your Fireblocks Customer Success Manager or send an email to [CSM@fireblocks.com](mailto:CSM@fireblocks.com).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateFullTravelRuleTransactionTest() throws ApiException {
        TravelRuleValidateFullTransactionRequest travelRuleValidateFullTransactionRequest = null;
        TravelRuleValidateTransactionResponse response = api.validateFullTravelRuleTransaction(travelRuleValidateFullTransactionRequest);

        // TODO: test validations
    }
    /**
     * Validate Travel Rule Transaction
     *
     * Validate Travel Rule transactions.  Checks what beneficiary VASP details are required by your jurisdiction and the beneficiary&#39;s jurisdiction.  **Note:** The reference content in this section documents the Travel Rule beta endpoint. The beta endpoint includes APIs that are currently in preview and aren&#39;t yet generally available.  To enroll in the beta and enable this endpoint, contact your Fireblocks Customer Success Manager or send an email to [CSM@fireblocks.com](mailto:CSM@fireblocks.com).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateTravelRuleTransactionTest() throws ApiException {
        TravelRuleValidateTransactionRequest travelRuleValidateTransactionRequest = null;
        TravelRuleValidateTransactionResponse response = api.validateTravelRuleTransaction(travelRuleValidateTransactionRequest);

        // TODO: test validations
    }
}
