name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Fireblocks API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
        distribution: [temurin, oracle]
        exclude:
          # Oracle JDK is only supported for JDK 17 and later
          - java: 11
            distribution: oracle
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --no-transfer-progress --file pom.xml -DskipTests
