name: Publish Maven

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Configure GPG Key
        run: |
          echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode | gpg --import --batch
      - name: Publish package
        run: mvn --batch-mode deploy -Dgpg.passphrase='${{ secrets.GPG_PASSWORD }}'
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_OSSRH_TOKEN }}
